### ISSUE TITLE
VRAM 31MB

### ISSUE THREAD

**Issue by digivish** [zearp/Nucintosh#10]
The install went perfect. I have a slightly different board in the same series. After Install VRAM shows 31MB and performance is painfully slow with the animations/Windows etc. Do you have a setting or a fix for the 620 video card?

**Comment by zearp** [comment]
What model do you have? You may have to change than just the framebuffer settings.

Try setting ```AAPL,ig-platform-id``` to ```00001659``` and reboot. If that doesn't work it might also be needed to spoof a device id ```16590000```. If that also doesn't work it probably needs another platform id. Let me know how it goes.

![Screenshot 2020-11-18 at 01 43 59](https://user-images.githubusercontent.com/63272687/99467871-95edcc00-293f-11eb-8e02-39a60500e3ee.png)

**Comment by zearp** [comment]
What model do you have? You may have to change more than just the framebuffer settings.

Try setting ```AAPL,ig-platform-id``` to ```00001659``` and reboot. If that doesn't work it might also be needed to spoof a device id ```16590000```. If that also doesn't work it probably needs another platform id. Let me know how it goes.

![Screenshot 2020-11-18 at 01 43 59](https://user-images.githubusercontent.com/63272687/99467968-c7ff2e00-293f-11eb-9216-1b24d1b35c99.png)

**Comment by digivish** [comment]
Just wanted to report back that 00001659 and the addition of device-id worked perfectly. The UHD620 now reports 2048 and everything works fantastic. I was on a Dawson Canyon 8th gen i7 NUC.

Thanks a ton!!

**Comment by zearp** [comment]
I'm happy it works!

You may have to make some more changes though. Like creating a new usb map and new ACPI patches. I don't know the differences between Dawson Canyon and Coffee Lake NUCs but I assume there are differences. Some may require changes in the config/ACPI patches.

I could check/help out but I would need a clean DSDT dump, clean as in made without any patches applied. You can dump it in Windows or Linux pretty easily. With that I can verify ACPI patches and such. My worry is the Thunderbolt patch. The NUC10 has a different Thunderbolt controller so your NUC7 may also have a different controller from the NUC8.
