### ISSUE TITLE
macOS Ventura Update

### ISSUE THREAD

**Issue by ajai-akkarapaka** [zearp/Nucintosh#100]
Hi Zearp,

W@nderful support and great job from you. Its been a longtime since I posted here for a query or issue.
The thing is now that Ventura is released and its showing as an update on the NUC Mac with a file size of 3GB. I want to know whether its safe to upgrade the normal update way or should we download the whole OS package and install it clean and copy the data.. Confused as the later is a time tedious and the former is an easy method.
Suggest your followers the best way to upgrade 👍 
Thanks again for you hard work
![Screen Shot 2022-10-27 at 12 10 21 AM](https://user-images.githubusercontent.com/85277762/198109380-75e3d571-0e59-44fd-8d05-3703049fc1a3.jpg)

**Comment by ajai-akkarapaka** [comment]
Thanks..
Will try updating the system and post the results.

Regards

**Comment by ajai-akkarapaka** [comment]
Done.. everything updated correctly and all fine.
Thanks again
![Screenshot 2022-10-27 at 4 56 57 PM](https://user-images.githubusercontent.com/85277762/198272456-9a9f119e-94bc-48cb-be66-6ecf51036c12.jpg)

**Comment by ajai-akkarapaka** [comment]
👍

**Comment by aacassandra** [comment]
hi @ajai-akkarapaka and @zearp , can anyone guide me, how to do update for AirportItlwm kext? thankyou

**Comment by zearp** [comment]
Download the Ventura version of the kext and replace the Monterey one before booting into the Ventura installer. You can find them in the stuff folder.

**Comment by zearp** [comment]
New release now with Ventura compatible Intel wireless driver as default.

https://github.com/zearp/Nucintosh/releases/tag/v3.9

**Comment by aacassandra** [comment]
@zearp , im sorry, im forgot about that. What do you mean: "Ventura installer" on the flashdrive and I open it on boot by pressing command + R ?

**Comment by aacassandra** [comment]
> New release now with Ventura compatible Intel wireless driver as default.
> 
> https://github.com/zearp/Nucintosh/releases/tag/v3.9

Thankyou bro, i will try this.

**Comment by aacassandra** [comment]
![Screenshot 2022-10-30 at 21 48 43](https://user-images.githubusercontent.com/29236058/198885089-3ff57df8-9466-4edf-b589-7520425fb063.png)

Thankyou @zearp

**Comment by aacassandra** [comment]
![mta](https://user-images.githubusercontent.com/29236058/198885329-a7e11bf2-944f-411e-8cde-777d87fd64d5.jpg)

Thankyou @zearp

**Comment by aacassandra** [comment]
Hi @zearp , seems internet sharing ethernet to wifi doesn't work

**Comment by zearp** [comment]
Sounds like a macOS problem not a problem caused by the EFI.

**Comment by zearp** [comment]
Sharing internet from ethernet to wireless works as expected with Apple Airport/Broadcom cards. The only difference in setup I noticed was that with Intel the drop down menu to select a wifi channel was empty when it wasn't using Airport cards. My guess would be that it doesn't support AP mode at all but I don't know if it worked in earlier macOS versions or not.

**Comment by zearp** [comment]
Someone has opened an issue about the slowness of wifi connecting;

https://github.com/OpenIntelWireless/itlwm/issues/823

I can't find any info on AP mode and these Intel wifi cards. It might be supported by the hardware but not implemented in the kext. Not sure if they would add it as it might be a lot of work for something rarely used.

**Comment by aacassandra** [comment]
> Sharing internet from ethernet to wireless works as expected with Apple Airport/Broadcom cards. The only difference in setup I noticed was that with Intel the drop down menu to select a wifi channel was empty when it wasn't using Airport cards. My guess would be that it doesn't support AP mode at all but I don't know if it worked in earlier macOS versions or not.

yes, in the previous version it didn't work either. thanks for the information.

but, search wifi feels long and difficult to connect. I've tried restarting the wifi and it's the same. takes up to 3-8 minutes to be able to connect to wifi. is this a bug?

**Comment by zearp** [comment]
It is a known issue. I linked to it above. I don't make the kexts so we can only wait for a fox form the creators.

**Comment by zearp** [comment]
It is a known issue. I linked to it above. I don't make the kext so we can only wait for a fix from the creators.

**Comment by zearp** [comment]
You can use itlwm.kext instead as a fix but it needs an app called Heliport to connect to a network. It is not integrated into the OS like AirportItlwm is.

https://github.com/OpenIntelWireless/HeliPort/releases/download/v1.5.0-alpha/HeliPort.dmg

https://github.com/zearp/Nucintosh/raw/master/Stuff/itlwm.kext.zip

**Comment by weijiaming** [comment]
> Thank you!
> 
> Updating with the small update should be fine, if anything goes wrong Software Update will download the full installer on its own. You can also download it yourself from here:
> 
> https://swcdn.apple.com/content/downloads/25/16/012-92138-A_KGGGN26YQB/d0kr042ixfvkboeft8qt2i3aclr5bx1e6p/InstallAssistant.pkg
> 
> Be sure to replace the AirportItlwm kext file before you install the update/boot into Ventura. Using a non-matching version can make booting freeze.
> 
> https://github.com/zearp/Nucintosh/raw/master/Stuff/AirportItlwm.kext-Ventura.zip

Is the same update steps for BCM94360CS2 wireless card NUC? thank you!

**Comment by zearp** [comment]
That card is natively supported so you can remove all the Intel kexts and disable wifi/bluetooth in the BIOS. It is also needed to delete the HS07 block in the usb map; https://github.com/zearp/Nucintosh/blob/02c221031bbe3845871f2016de25a7a6c6f33e86/EFI/OC/Kexts/USBPorts.kext/Contents/Info.plist#L130-L136

**Comment by weijiaming** [comment]
> That card is natively supported so you can remove all the Intel kexts and disable wifi/bluetooth in the BIOS. It is also needed to delete the HS07 block in the usb map;
> 
> https://github.com/zearp/Nucintosh/blob/02c221031bbe3845871f2016de25a7a6c6f33e86/EFI/OC/Kexts/USBPorts.kext/Contents/Info.plist#L130-L136

Update from System Settings failed，but I successfully updated Ventura from App Store, and the download size is 12.5GB.

The problem now is，the system occasionlly crashes when inserting USB storage devices.

**Comment by zearp** [comment]
I've had updates failing from SoftWare Update for a while, the small update would fail and then it would download the full 12gb installer. I've not had any issues with inserting usb devices and getting reboots. I'm currently running Ventura on 2 NUCs. Can you try usb in another OS and see if that works? I've never experienced such instant reboots on any hackintosh I built over the years. It may be a hardware thing but not sure until you try in another OS (or even the bios).

**Comment by zearp** [comment]
I've had updates failing from Software Update from time to time with the beta's but it has not happened since the final yet. In the beta's the small update would fail and then it would download the full 12gb installer. I've not had any issues with inserting usb devices and getting reboots. I'm currently running Ventura on 2 NUCs. Can you try usb in another OS and see if that works? I've never experienced such instant reboots on any hackintosh I built over the years. It may be a hardware thing but not sure until you try in another OS (or even the bios).

**Comment by weijiaming** [comment]
> 

Probably It was a software compatibility issue. I noticed that Paragon NTFS For Mac wouldn't start properly after upgrading to Ventura, so I upgraded it to the latest version.  The reboot issue hasn't reproduce so far.

**Comment by zearp** [comment]
Ohh good find! Maybe the driver it uses needed to be updated and without the update it would freak out, panic and reboot. On login the next time sometimes macOS will show you a dialog about a crash. You can then find out more details about what exactly happened. But thats not needed anymore!

**Comment by weijiaming** [comment]
> That card is natively supported so you can remove all the Intel kexts and disable wifi/bluetooth in the BIOS. It is also needed to delete the HS07 block in the usb map;
> 
> https://github.com/zearp/Nucintosh/blob/02c221031bbe3845871f2016de25a7a6c6f33e86/EFI/OC/Kexts/USBPorts.kext/Contents/Info.plist#L130-L136

One more thing to be confirmed.  Is all Intel kexts refer to IntelBluetoothFirmware.kext and anything else?  

The system crashed twice when connecting my iPhone11 as personal hotspot through type-c. And there was no response sliding the mouse or typing on the keyboard. Unfortunately no crash logs were found.

**Comment by zearp** [comment]
Without panic and crash logs there’s nothing I can do. I’m also not able to try and reproduce it as I don’t have that phone. Did it happen on Monterey too?

Ventura still needs fixes and they won’t be coming soon due to holiday season. Best to stick to Monterey if you need a stable system. 

Yes, all Intel includes all of them. With both wireless and bluetooth disabled in the bios there is no need to load the kexts and it could cause issues.

**Comment by weijiaming** [comment]
> Without panic and crash logs there’s nothing I can do. I’m also not able to try and reproduce it as I don’t have that phone. Did it happen on Monterey too?
> 
> Ventura still needs fixes and they won’t be coming soon due to holiday season. Best to stick to Monterey if you need a stable system.
> 
> Yes, all Intel includes all of them. With both wireless and bluetooth disabled in the bios there is no need to load the kexts and it could cause issues.

It was very stable on Monterey 12.6.1. Perhaps the only thing I can do is wait...
