### ISSUE TITLE
Can you add monterey support using MinKernel and MaxKernel?

### ISSUE THREAD

**Issue by chepe263** [zearp/Nucintosh#102]
According to the [Dortania Guide](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake.html#kernel), it is possible to have different kext (AirportItlwm, for instance) to load for different kernels or MacOS versions. So it would be possible to add AirportItlwm for Monterey and AirportItlwm for Ventura in the same efi but limit what load using MinKernel and MaxKernel.

Do you think this is something we can have in the future?

**Comment by zearp** [comment]
Maybe as a separate release. The EFI will become larger and some of my NUCs have a relatively small EFI partition. A kext swap only has to be done once unless you want to multi boot multiple macOS versions.

Personally I use itlwm for that and Heliport as thats one small kext will work with any macOS version. The min/max kernel setting is good way too. A multi-boot release shouldn't be too difficult!

I'll look into it for sure. Maybe multi-boot + simple dark mode gui as you'll see the picker often when multi booting.

**Comment by zearp** [comment]
I won’t be making a mixed version release anymore but anyone can submit a PR to add it.
