### ISSUE TITLE
Unknown Card Type in the Status Bar

### ISSUE THREAD

**Issue by amsterford** [zearp/Nucintosh#105]
Hello!
I just installed macOS Ventura 13.0.1 on my NUC8I3BEK2 and found interesting issue in the status bar – an icon with 'Unknown Card Type' title. I tried to disable Thunderbolt, LAN, HDMI-audio and smth else... Nothing helps.
I also tried to choose 'Power off Card' option and remove this icon from the status bar by dragging it away holding the cmd key – it is still appearing every single time I boot the system.
Can you suppose what could cause it? Nothing like this has ever happened with macOS Monterrey on this NUC.
Thank you very much! :)

![Screenshot 2022-12-04 at 16 02 52](https://user-images.githubusercontent.com/94016340/205501827-0c5b14bc-d709-4f7c-aea1-a846d3aa788c.png)

**Comment by zearp** [comment]
This is not an issue but how it's supposed to be. You can hide it by installing HiddenBar as it can't be hidden without sacrificing security in newer macOS anymore. You may also be able to get rid of it by disabling bluetooth, wifi and the sd card slot in the bios.

In older maCOS versions it was very easy to hide the icon, but those days are over lol. Apple has locked down the system volume to the max which is great for security and bad for customising and removing icons like this.
