### ISSUE TITLE
WiFi doesn't connect after waking up

### ISSUE THREAD

**Issue by amsterford** [zearp/Nucintosh#107]
Hello again!
One more question here. Sorry if I've missed something during installation. I hadn't such sad issue before on Monterey, but now it's a regular trouble.

macOS Ventura 13.0.1
NUC83BEK2

System goes to sleep – then WiFi is trying to connect, but no luck. I have to reboot the computer. Is there any simple solution?

Thank you!

**Comment by zearp** [comment]
Intel wireless I assume. It’s a known Ventura related bug that needs to be fixed upstream. In mine it connects after a 5-15 minutes on boot or wake but it is not stable or reliable. 

The devs are working on it. Last commit was 17 hours ago. I’ll update mine later today to try it and post it here so you can try if the fixes solved it for you.

**Comment by zearp** [comment]
I've updated the kexts but it didn't fix the issue of slow connecting wifi. To be fair, I don't see anything in their commits that would indicate it was fixed.

https://github.com/OpenIntelWireless/itlwm/commits/master

The issue relating to this is also still open.

https://github.com/OpenIntelWireless/itlwm/issues/823

I guess we have to patient for both wifi to connect and a fix to be released. You can try the new kext by replacing yours with this one: https://github.com/zearp/Nucintosh/raw/master/Stuff/AirportItlwm.kext-Ventura.zip

I will close this issue as I can't fix it myself but be sure I'll keep an eye on this.

Most of my NUCs are stock and use the Intel wifi/bluetooh + NMVe drive and only a few have Apple Airport card in the m.2 slot and a normal sata ssd. The Airport cards didn't give me any issues but thats to be expected from real Apple hardware.
