### ISSUE TITLE
Hackintosh can't share net with wifi or RJ45

### ISSUE THREAD

**Issue by sesameman** [zearp/Nucintosh#108]
Please provide the follow information:

- Steps to reproduce the issue -- this is crucial
- macOS version and optionally the build number
- Any changes you made to the config and/or EFI other than serials/etc
- Any logs related to the issue if applicable

I just boot with this efi, and it just can't share .

version: macOS 12.6

wi-fi-in  rj45-out ,can't.
rj45-in wifi-out ,can't too.

**Comment by zearp** [comment]
For wireless sharing to work you'll going to need an Apple Airport card. The Intel wireless is not supported by macOS officially so you can't use those kind of things unless they are added upstream by the developers of the Intel wireless kext. Those developers already added some functionality thats normally exclusive for Apple Airport cards like some continuity features. I don't know if they plan on adding internet sharing to their driver.

https://github.com/OpenIntelWireless/itlwm

Internet sharing works expected for me on my NUCs with Apple Airport cards and doesn't work on NUCs with Intel wireless.

**Comment by ffffwh** [comment]
Confirmed.

BTW: Is there any third party apps do this?

**Comment by zearp** [comment]
There might be apps that can provide a hotspot, they do for Windows. But chances are those apps just use macOS internal internet sharing anyways.

It might be possible if you do the fireballing bit manually. It is just simple NAT sharing. I would guess the procedure is the same as with iptables and the likes but then for Apple's version of it, ```socketfilterfw```.

```
% /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate --getblockall --getallowsigned --getstealthmode 
Firewall is disabled. (State = 0)
Block all DISABLED! 
Automatically allow signed built-in software ENABLED 
Automatically allow downloaded signed software ENABLED 
```

It is disabled by default but in theory it should be possible to setup the same sort of firewall rules manually that clicking "share internet" does. But then it might still not work if the firewall's kernel driver doesn't support NAT and then there's the issue of putting the Intel wifi in AP mode. It might also not be supported by the kext. I don't think the devs of that driver focus on those things much.

I had some headaches with AP mode on Linux and sharing internet the same way a while ago. The driver from the manufacture didn't support AP mode at all then some 3rd party driver did but then iptables NAT didn't work with that driver. It took an afternoon of compiling drivers and trial and error to get it to work. It was a pain lol.

I couldn't find much useful info on socketfilterfw and NAT. Just a bare man page.

https://www.unix.com/man-page/mojave/8/socketfilterfw/
