### ISSUE TITLE
Asking for help with refresh rate of the monitor.

### ISSUE THREAD

**Issue by naryfa** [zearp/Nucintosh#110]
Hello,

So I'm still on NUC8i7BEH with Monterey 12.5.1, OC 0.8.4 and an LG 27" 27MK600M-W display that runs at 75Hz.

Very often, while scrolling websites in any browser, I get a visible stutter and I don't know it has to do with the display driver or any OC settings to the graphics card. Seems like the refresh rate is dropping or something. I have no clue how to test this. 

Have you experienced anything similar on a FHD monitor (if you even use one at this point)? I didn't have this problem in Mojave.

Any insights would be appreciated.

**Comment by zearp** [comment]
Check if the monitor actually runs at 75hz using the OSD. It should be smoother than 60hz but not by much. I've got mine set to 120hz as going above it breaks 32bit colours (in both Windows and macOS) for me. It's likely a limitation of the screen and not a cable or config issue.

But sometimes a cable can matter too. I've recently tested it with HDR where some cables simply didn't give me the option at all and others did but still didn't work properly.

Apple recommends some kind of validated cable for video signals. If the cable is certified for Dolby Vision it gives you the best chances but no guarantees.

There are also 3rd party utils to force refresh rates but I wouldn't recommend those. If your refresh rates aren't working properly or not listed it is better to try and patch the EDID first.

![refresh rates](https://user-images.githubusercontent.com/63272687/208350746-325c3150-1318-4f4c-8194-0f14298ddbbd.png)

If I use the cable that came with my screen the max refresh rate is 144hz for some reason. No issues in Windows. macOS can be fussy and weird. Even when you buy their own expensive stuff people have lots of issues with refresh rates, HDR and also copyright/drm signals not being passed on properly. The Apple forums are full of people with these issues. It is one of the drawbacks of macOS; compatibility can be problematic.

This is a can't fix it issue so I wish you good luck, but please let me know if you manage to solve it by patching EDID or using 3rd party tools!

**Comment by naryfa** [comment]
Hey, 

Thank you for responding. I will try patching EDID, although it seems to be recognized as LG FULL HD.

Like I mentioned, nothing changed hardware-wise since macOS Mojave, so I'd think it has to do with the OS itself.

I will research more, report back if I get anywhere with it. 

Thank you again.
