### ISSUE TITLE
Green screen / Wrong colors

### ISSUE THREAD

**Issue by Pondake** [zearp/Nucintosh#116]
Please provide the follow information:

- Steps to reproduce the issue -- this is crucial
Install according to guide, use an external monitor (Dell U2515H), no extra config.
- macOS version and optionally the build number
Ventura 13.1
- Any changes you made to the config and/or EFI other than serials/etc
When I saw the colors were incorrect, I tried updating whatevergreen kext but without results.
I also installed SwitchResX and changed colors to "Million colors" instead of "Billion colors". But now my screen is permanently green :) 
- Any logs related to the issue if applicable
Would love to share if I knew how

I also noticed that the system was a bit laggy when minimizing windows, which shouldn't be the case. 
This post seems to have the same problems but I couldn't figure the solution in this scenario: 
https://www.reddit.com/r/hackintosh/comments/pmw7ut/fake_colours_on_oc_073_after_installation_of_big/

**Comment by zearp** [comment]
This is not an issue or bug with the EFI. Most likely with the cables used and/or conversion or maybe a firmware loaded form another OS. My macOS always gets a purple tint when I booted into Linux. It's a firmware thing as powering off and booting up cold fixes it. You can try disabling loading Apple's GuC firmware but it may not do anything other than reduce performance of video encoding/decoding. To disable loading of that firmware remove ```igfxfw=2``` from the frame buffer settings.
