### ISSUE TITLE
Broadcom bluetooth not working

### ISSUE THREAD

**Issue by zearp** [zearp/Nucintosh#122]
I have full working Ventura 13.3.1 system now bar bluetooth thanks to you. I am using an adapter with a USB header connected to a BCM94360CS2. The wifi is working perfectly and I think the device is showing for bluetooth but will a NULL value.

Address:	NULL
  State:	Off
  Chipset:	BCM_4350C2
  Discoverable:	Off
  Firmware Version:	v0 c0
  Supported Devices:	0x382039 < HFP AVRCP A2DP HID Braille AACP GATT SerialPort >
  Transport:	USB
  Vendor ID:	0x004C (Apple)

Any idea how to enable this please as I have tried to follow your instructions but I am a bit lost now!

_Originally posted by @richarddcrossley in https://github.com/zearp/Nucintosh/issues/90#issuecomment-1509984652_

**Comment by richarddcrossley** [comment]
Sorry I was late in replying (I have been ill). What file information and from which file do I need to extract so you can help to get this card working please?

**Comment by zearp** [comment]
Please provide the info I requested in my reply to you and also check out my suggestions. You might be able to fix it yourself without further assistance.

https://github.com/zearp/Nucintosh/issues/90#issuecomment-1509989374

Thanks and be well!
