### ISSUE TITLE
Bluetooth being identified but not working. 

### ISSUE THREAD

**Issue by imAlegitHacker420** [zearp/Nucintosh#125]
Hey Zearp, 

As always big thanks for all your assistance on this project. Kinda scratching my head on this one. 

I purchased the BCM94360CS2 and an adapter card of Aliexpress with the correct JST connector. The Wifi worked out of the box on the next reboot but I've had no luck with Bluetooth, which is the only thing im missing for using my AirPods. 

Attached is a few screenshots and my EFI folder. Hope you have some input. 

![image](https://user-images.githubusercontent.com/57121944/236642365-7d77c55f-6089-41e3-8e44-94617454fb56.png)
![image](https://user-images.githubusercontent.com/57121944/236642367-6d459b7d-df66-46f1-9208-6ef43a69ce90.png)

[EFI.zip](https://github.com/zearp/Nucintosh/files/11413167/EFI.zip)

Cheers! 
Michael :)

**Comment by zearp** [comment]
Thanks for the kind words.

The usb map looks good, the internal 'hub' used by the Intel combo card is gone, which is needed. I assume in your bios you disabled wireless/bluetooth as well. Leaves the kexts. Those need some trimming and/or disabling. Whatever you prefer. Keep in mind running a ProperTree snapshot might enable kexts that were disabled yet not removed from the kext folder but I'm not 100% sure about it. Just something to keep in mind if you opt to keep the kexts in place.

You will need to disable or remove:
```
BlueToolFixup.kext
```
I expected to paste in more but I see the Intel wifi/bt ones were removed from the config but not the kext folder, which is fine. It only loads those kexts defined in the config. Once you disabled the Fuxup kext it should work. The card you bought is the one I use myself in many hacks and it's natively supported buy macOS. You need no drivers or config changes for it.

Let me know how it went!

To get it working under Windows you either need Bootcamp drivers or some drivers from the Fenvi site who uses this chipset too but sells it at double the price 🤑 If you can't find it or it's been removed let me know. I have a copy somewhere that will work on 64bit Windows 10/11.

**Comment by zearp** [comment]
Thanks for the kind words.

The usb map looks good, the internal 'hub' used by the Intel combo card is gone, which is needed. I assume in your bios you disabled wireless/bluetooth as well. Leaves the kexts. Those need some trimming and/or disabling. Whatever you prefer. Keep in mind running a ProperTree snapshot might enable kexts that were disabled yet not removed from the kext folder but I'm not 100% sure about it. Just something to keep in mind if you opt to keep the kexts in place.

You will need to disable or remove:
```
BlueToolFixup.kext
```
I expected to paste in more but I see the Intel wifi/bt ones were removed from the config but not the kext folder, which is fine. It only loads those kexts defined in the config. Once you disabled the fixup kext it should work. The card you bought is the one I use myself in many hacks and it's natively supported buy macOS. You need no drivers or config changes for it.

Let me know how it went!

To get it working under Windows you either need Bootcamp drivers or some drivers from the Fenvi site who uses this chipset too but sells it at double the price 🤑 If you can't find it or it's been removed let me know. I have a copy somewhere that will work on 64bit Windows 10/11. Thanks for the kind words.

The usb map looks good, the internal 'hub' used by the Intel combo card is gone, which is needed. I assume in your bios you disabled wireless/bluetooth as well. Leaves the kexts. Those need some trimming and/or disabling. Whatever you prefer. Keep in mind running a ProperTree snapshot might enable kexts that were disabled yet not removed from the kext folder but I'm not 100% sure about it. Just something to keep in mind if you opt to keep the kexts in place.

You will need to disable or remove:
```
BlueToolFixup.kext
```
I expected to paste in more but I see the Intel wifi/bt ones were removed from the folder but not config. Once you disabled/removed the fixup kext it should work. The card you bought is the one I use myself in many hacks and it's natively supported buy macOS. You need no drivers or config changes for it.

I suggest you remove the entries for the Intel stuff from the config, to avoid errors on boot and confusion. I did it already in the attached config.

Let me know how it went!

To get it working under Windows you either need Bootcamp drivers or some drivers from the Fenvi site who uses this chipset too but sells it at double the price 🤑 If you can't find it or it's been removed let me know. I have a copy somewhere that will work on 64bit Windows 10/11. 

[config.plist.zip](https://github.com/zearp/Nucintosh/files/11413444/config.plist.zip)

**Comment by zearp** [comment]
The usb map looks good, the internal 'hub' used by the Intel combo card is gone, which is needed. I assume in your bios you disabled wireless/bluetooth as well. Leaves the kexts. Those need some trimming and/or disabling. Whatever you prefer. Keep in mind running a ProperTree snapshot might enable kexts that were disabled yet not removed from the kext folder but I'm not 100% sure about it. Just something to keep in mind if you opt to keep the kexts in place.

You will need to disable or remove:
```
BlueToolFixup.kext
```
I expected to paste in more but I see the Intel wifi/bt ones were removed from the folder but not config. Once you disabled/removed the fixup kext it should work. The card you bought is the one I use myself in many hacks and it's natively supported by macOS. You need no drivers or config changes for it.

I suggest you remove the entries for the Intel stuff from the config, to avoid errors on boot and confusion. I did it already in the attached config.

Let me know how it went!

To get it working under Windows you either need Bootcamp drivers or some drivers from the Fenvi site who uses this chipset too but sells it at double the price 🤑 If you can't find it or it's been removed let me know. I have a copy somewhere that will work on 64bit Windows 10/11. 

[config.plist.zip](https://github.com/zearp/Nucintosh/files/11413449/config.plist.zip)

**Comment by imAlegitHacker420** [comment]
Hey Zearp,

**Comment by imAlegitHacker420** [comment]
Hey zearp, 


Re-attatched my new EFI Folder, hope it's still in order. 

This is strange. Bluetooth is System settings is still greyed out and won't let me click the radio button to enable it. System info still reports as NULL: 

![image](https://user-images.githubusercontent.com/57121944/236670754-e72a57fe-8f0e-4987-b99e-ab8f5602ccd0.png)

Hackintool Still sees the module, so at leas the board is working: 

![image](https://user-images.githubusercontent.com/57121944/236670802-8dd53b53-964e-4113-8d3c-a9b31925add2.png)

But the HS07 Port won't show as an active port, which is strange considering I deleted the block as you explained in the USB map:

![image](https://user-images.githubusercontent.com/57121944/236670859-52665ba4-0eb1-4ceb-b7ea-91fee67f2bc1.png)

 EFI: 
 
[EFI.zip](https://github.com/zearp/Nucintosh/files/11414579/EFI.zip)

**Comment by imAlegitHacker420** [comment]
What's also interesting @zearp is that in IOService im not seeing the usb port HS07 being mapped to anything, that value doesnt exist.

![image](https://user-images.githubusercontent.com/57121944/236671855-0e3b40c3-7cfd-4e48-a533-09451a6e68d3.png)

Im not too familiar with IOService however.

**Comment by zearp** [comment]
Hackintool caches the ports. So see the current ports it detects select them all, delete them and click the refresh button.

I really have no idea why it's not working. It doesn't need any configuration or kexts. We have to remove some but nothing needs to be added as it's supported by default.

Can you confirm the bluetooth works in Linux or Windows? Just to exclude the usb cable going from the adapter to the motherboard has an issue.

**Comment by zearp** [comment]
Hackintool caches the ports. To see the current ports it detects select them all, delete them and click the refresh button.

I really have no idea why it's not working. It doesn't need any configuration or kexts. We have to remove some but nothing needs to be added as it's supported by default.

Can you confirm the bluetooth works in Linux or Windows? Just to exclude the usb cable going from the adapter to the motherboard has an issue.

**Comment by imAlegitHacker420** [comment]
Downloading Linux to see if it works in there, will report back. Certainly a strange issue.

**Comment by zearp** [comment]
If you remove all the usb ports in Hackintool and refresh the list can you see the usb bluetooth device like in mine? Your cached list is rather long. I think I have the same card in this machine or maybe a slightly diff model I took from a MacBook Air. 

![Screenshot 2023-05-07 at 13 19 55](https://user-images.githubusercontent.com/63272687/236674416-6a1bb4b1-db91-4a06-96ee-4fbb67ee21d5.png)

**Comment by imAlegitHacker420** [comment]
This is what I personally get when I remove and refresh the list: 

![Screenshot 2023-05-07 at 12 22 13](https://user-images.githubusercontent.com/57121944/236674471-826e36d5-5e81-4063-9263-6da6e0b67655.png)

**Comment by zearp** [comment]
I don't see any BCMxxxx bluetooth usb device. I recall someone else having the same kind of issue and it in the end the little cable running from the card to there motherboard had some issue. I'm not too sure what it was but they ordered a new one. You could try resolder the connections of it if you can. It should at least detect the usb device plugged in.

Even with no changes at all to the config you should be able to see the usb device there. In Linux you can do ```lsusb``` but I don't think it will show up there either cuz it doesn't show in Hackintool. But who knows it could be (albeit a small chance) something in the config but I fear there is some hardware problem.

**Comment by zearp** [comment]
I don't see any BCMxxxx bluetooth usb device. I recall someone else having the same kind of issue and it in the end the little cable running from the card to the motherboard had some issue. I'm not too sure what it was but they ordered a new one. You could try resolder the connections of it if you can. It should at least detect the usb device plugged in.

Even with no changes at all to the config you should be able to see the usb device there. In Linux you can do ```lsusb``` but I don't think it will show up there either cuz it doesn't show in Hackintool. But who knows it could be (albeit a small chance) something in the config but I fear there is some hardware problem.

**Comment by zearp** [comment]
It should show up on either ```HS05``` or ```HS06``` which are the small internal usb ports. Also make sure those internal usb headers aren't disable in the bios. They should be enabled by default.

**Comment by imAlegitHacker420** [comment]
Yeah, that’s what I figured. I think (annoyingly) this a usb connection issue. Which is frustrating. The solder joints look great on the board from Aliexpress. 

all usb headers are enabled in bios settings too. They just don’t seem to be picking up the connection. Either my JST female connectors on the mobo are fucked, in which case I don’t know what to do then, or I gotta wait for another replacement from China.

**Comment by imAlegitHacker420** [comment]
What's stopping my from soldering the wires out of the converter board to a usb type a male connector and just plugging it in from the outside? (under the assumption the board isn't the issue). 

Does it have to be connected internally, surely usb is usb in either sense?

**Comment by imAlegitHacker420** [comment]
Some Linux testing shows nothing is lsusb, now I gotta decide what will be best moving forward. 

Do you know if these internal usb headers are prone to being shorted/killed? I don’t want to invest and wait again just for it to not work bc these ports are dead :(

**Comment by zearp** [comment]
They are standard jst connectors and unless you're rough they will be fine. 

Most likely your adapter card needs some soldering. You can be certain if you have a multimeter and check the continuity of signals. It sucks but some of these boards from China don't have the best build quality and/or in shipping things come apart.

The wifi part works because it connects directly to pci lanes. The usb part is a fragile thin cable. It wouldn't be too difficult to replace it too. But I don't know about your soldering skills. 

The cable just carries data and power. It's very basic. You could try and carefully wiggle the wire a bit and see if a device pops up in Hackintool. If it does that's a clear indicator the cable has a break in it somewhere.

Still suck you received hardware not working fully. Hope you get it resolved.
