### ISSUE TITLE
Bluetooth broke after 3 years of flawless operation

### ISSUE THREAD

**Issue by ezrapeace** [zearp/Nucintosh#132]
I first set this up in May-ish of 2020, with Catalina and Clover, then updated to Monterey in Nov of 2021, and switched to OpenCore at that time. Apart from a hiccup during installation of Monterey it has been a completely non-eventful experience. Literally no issues. Until now 2 years later, suddenly the bluetooth no longer seems to detect any devices nor list already paired devices.

I believe the EFI version I'm running is v3.3 since the first update email I got was v3.4. Monterey is 12.2.1 and I have updates turned off since installation and stable update back in Feb 2022, I want to say. 

Other mission stats: NUC8i3BEH with 16 GB RAM and a 255 GB SSD

Any guidance you can give for troubleshooting would be much appreciated as the original guide I used to set this up has since been taken down (https://bit.ly/44eOiWQ), and I'd rather not start guessing and making a bigger mess. I saw there are a couple repos that are used to get 3rd party wifi/bt working but this is native intel and just worked out of the box. Not sure how to tackle this, if you have any ideas? 

Thanks so much,
EP

**Comment by zearp** [comment]
Suddenly out of blue without any changes or updates would indicate hardware failure. Bluetooth was broken by some macOS update. There’s an issue about it with a new EFI zip that should fix it.

**Comment by zearp** [comment]
The fixed EFI may also work for Monterey too but you’ll have to replace AirportItlwm as with a compatible version from the Stuff folder. Ventura is included by default. 

If it doesn’t work then we’ll need logs because I’m no longer using Monterey on my NUCs so not able to test anything myself.

**Comment by ezrapeace** [comment]
Re: hardware; I did try to use a USB adapter, but it only now occurred to me that that wouldn't work until I loaded the kexts for 3rd party BT.

Ok, so just so I'm sure I understand, option 1 is to update the EFI to the latest version, but it will require to replace the Airportltlwm kext from the Stuff folder. Option 2 is to submit logs for possible insight (which logs, lmk), and the nuclear option is 3 to upgrade to Ventura, do I have that correctly?

I will start looking for the OpenCore update now (it's been a minute since I've had to do all this, feels a bit foreign now). 

Thanks again for your help. You're the best in hackintosh!

**Comment by zearp** [comment]
Did problem start after an update or out of the blue without you doing anything?

**Comment by zearp** [comment]
Well I can't test if a recent update also broke bluetooth in Monterey but it did break on Ventura. So it is possible you also need to update the EFI to fix it.

Try this one and let me know, it has the bluetooth fixes and the Monterey Intel wireless driver in it.

[EFI.zip](https://github.com/zearp/Nucintosh/files/11869027/EFI.zip)

**Comment by ezrapeace** [comment]
It was completely out of the blue. My use of this machine is quite routine,
as it is my main workstation. One thing that I added to the routine
recently (in the last 4 months or so) was I started using Parrallels
desktop to access a couple apps that only run in Windows. But that's been
going flawlessly for months now. And even then I never shared the Bluetooth
or wifi connections to the Parrallels installation. I don't even use wifi
on this computer, altho it works fine.

**Comment by ezrapeace** [comment]
Ok thanks! I'll do it at the end of the day. Just in case I bungle it
(hopefully not).

But it's worth reiterating, no Apple updates whatsoever once I got Monterey
installed in early 2022. Unless Apple is sneaky-updating stuff without me
knowing it.

**Comment by zearp** [comment]
Unless you disabled it manually macOS will download and install certain updates if it deems them "important" enough by default. I turned it all off except checking for updates. This is from my Dell machine running Monterey:
![Screenshot 2023-06-26 at 15 07 09](https://github.com/zearp/Nucintosh/assets/63272687/9689bde5-4d69-4224-bdea-933b49ae4a61)

**Comment by zearp** [comment]
I see my Dell has Monterey 12.6.7 available, I'll install it and see what happens. Maybe it breaks bluetooth on mine too. But I use Broadcom in there so I think nothing will happen as Broadcom remains supported natively in Monterey and Ventura. For macOS Sonoma it's gonna be a different story because Appel decided to remove all support for Broadcom. Intel bluetooth/wireless was never officially supported.

What version of Monterey are you on exactly?

**Comment by ezrapeace** [comment]
That's how my software update settings look as well. It checks but does
nothing with what it finds.

My Monterey is on 12.2.1. Software Update shows Ventura as the available
update.

Something interesting was that in the details for Bluetooth the card is
detected as a 3rd party dongle. 3rd party is expected, but wasn't sure if
that it showed as a dongle was important?

[image: image.png]
[image: image.png]
[image: Screen Shot 2023-06-27 at 6.35.51 AM.png]
[image: Screen Shot 2023-06-27 at 6.38.58 AM.png]

**Comment by zearp** [comment]
Intel is 3rd party. I would suggest updating to the latest Monterey and also update the EFI. Then do some testing and log file reading.

I’ll repeat myself that if it really happened out of the blue it is likely hardware. I can’t see an images you attack to emails. The issues are online. It’s not a mailing list.

**Comment by zearp** [comment]
To update to the latest Monterey instead of Ventura click the "show more" thingy in the update screen and it should allow you to select the new Monterey instead. Once you are up to date we can gather some information but I'm worried it is a hardware thing. Try booting from a live Linux usb stick and see if bluetooth works there. Either way, without logs and such it is next to impossible for me to help you. If I have some free time I could try to install Monterey on one of my NUCs to see if I can reproduce it but I will be using the latest installer as thats what I have downloaded and my download speed is too slow to download an old 12GB installer just to reinstall macOS on one of my machines to test this issue.

**Comment by ezrapeace** [comment]
Brilliant. There was apparently a problem with my Ubuntu disk, but I was able to boot into a Windows 10 disk I had and connected (and played through) a bluetooth speaker fine.

Relieved it's not a hardware issue I guess. So that just leaves Monterey then (perplexed why now). What logs would you need? Happy to provide them. I'll update Monterey. Still working on how to update the EFI, since I remember nothing from when I did it 3 years ago. And the guide I used has since been taken down, so I have to rely on finding another one that "feels" like the one I used. I know EFI is critical so I'd rather not bollox it up lol

Q, how much work would it be to simply upgrade to Ventura? Or would I be inviting more trouble than it's worth (very likely)?

**Comment by ezrapeace** [comment]
![1](https://github.com/zearp/Nucintosh/assets/99253630/e23f39e9-1bed-4ed2-bc97-f7bbf65ad525)
![2](https://github.com/zearp/Nucintosh/assets/99253630/4dc0cd2c-e171-443d-aa10-f7b2debd0c9e)
![3](https://github.com/zearp/Nucintosh/assets/99253630/1873af30-3a34-4990-9d40-dd52a36c584d)
![4](https://github.com/zearp/Nucintosh/assets/99253630/a55b4fb2-1ef9-44d2-82e2-c8220d51a373)

**Comment by ezrapeace** [comment]
As bizarrely as this problem appeared, it seems to have vanished. I am now able to connect to bluetooth devices once again. All of my previously connected devices are still gone, but functionality seems to have self-restored. What could cause this? I guess if we had any idea it would have come up by now, but what a weird experience.

Anyway, thank you for your attention and effort, you really are the best. Have a fantastic day.
