### ISSUE TITLE
BCM94360CS2 Network Card to M Key PCle X4 M.2 NGFF Adapter Card

### ISSUE THREAD

**Issue by Supradry** [zearp/Nucintosh#135]
- NUC8i5BEHS
- Ventura 13.5

Hey mate, thanks for uploading your EFI, it's been of great help for my NUCintosh. Everything is working perfectly aside from the adapter card I bought which was recommended by your guide. Wifi works but bluetooth doesn't. Just wondering if you had to play around with anything? I reckon my adapter is faulty cos the bluetooth works in my MBA 2013. I've disabled all the kext related to wifi and bluetooth and it should just work natively but I can't get it to detect. Comes up with Null in system info. Any thoughts? This is my 4th hackintosh so I'm familiar with most of this. Just wanting to confirm if you think the adapter would be faulty too. Thanks

**Comment by zearp** [comment]
Bluetooth uses usb, you will need to connect a cable to one of the two small internal usb headers. Also be sure those internal headers are enabled in the bios. You could check in Windows or Linux if the bluetooth usb device is found with ```lsusb``` or device manager. If you use the EFI's usb port map then the internal headers are mapped already.

You do not need any extra kexts if you bought an Apple branded adapter pulled from a Mac/Macbook. Any other adapter may need additional kexts.

**Comment by zearp** [comment]
Bluetooth uses usb, you will need to connect a cable to one of the two small internal usb headers. Also be sure those internal headers are enabled in the bios. You could check in Windows or Linux if the bluetooth usb device is found with lsusb or device manager. If you use the EFI's usb port map then the internal headers are mapped already.

You do not need any extra kexts if you bought an Apple branded card pulled from a Mac/Macbook. Any other card may need additional kexts.

**Comment by Supradry** [comment]
The internal USB header is enable in the bios and I've used hackintool to remap the new USB ports. However, nothing new comes up in hackintool or in windows which leads me to believe it's a faulty adapter. Wifi works so the bluetooth just doesn't seem to be getting power. I'll either have to buy another adapter or will go to eBay to raise an issue for replacement.

**Comment by zearp** [comment]
Try a different os, it’s the easiest way. There was no need to remap usb ports but won’t hurt as long as you map the ports you use.

Someone else had a similar issue. I suspend the solder joints the usb cable is attached to the board with might not be good or the cable itself is damaged internally. They’re thin and fragile and can happen in shipping. If you have a multimeter and a soldering iron not too tricky to fix if it’s the cause.

Good luck!
