### ISSUE TITLE
Cannot boot without monitor

### ISSUE THREAD

**Issue by meienberger** [zearp/Nucintosh#14]
Thank you very much for your work ! It's working like a charm.
I'm trying to boot my Nucintosh but it will never work without a monitor connected and powered on.

**Comment by zearp** [comment]
That's weird!

I tried, but I can't reproduce it. This is pretty interesting though cuz I run one of my NUCs pretty much always headless. It sits on my workbench with nothing but power. I just use macOs's screen sharing to get to the desktop when I need to. I can't think of a reason as to why yours can't boot without a screen connected. I don't think there's any setting in the BIOS that would prevent it from booting.

It's gonna be tricky to figure out cuz without a screen we don't know whats going on or where it stops booting. Maybe its stuck in the picker? It happens very rarely when I test fresh installs; OpenCore doesn't select any entry and it just sits in the picker waiting. You could also enable the boot chime although I don''t know if there's an internal speaker to play it on and I don't think it's easy to route the audio to the jacks without diving in deeper. Just trying to think of ways to figure out where in the boot process it stops. If the chime sounds we know the OpenCore station was reached.

As a test can you boot with a screen attached and in the picker select your macOS and then press control + enter to set that entry as default? Also for good measure clear NVRAM, maybe something in there is acting up. You could also try removing the connector entries in the config but I doubt that will do anything. I'm not even sure if this has anything to do with OpenCore or macOS.

Can you boot Windows or Linux without a screen attached? I don't think think there's any halting stuff in the BIOS either. Like on my Dell systems many things can cause a "press F1 to continue" when booting. Which is detrimental for headless mode. If you can help me reproduce I can better help out. Let me know which steps you followed and hats different in your setup from mine. Any edits to the config or difference in BIOS settings?

**Comment by zearp** [comment]
This is pretty interesting though cuz I run one of my NUCs pretty much always headless. It sits on my workbench with nothing but power. I just use macOs's screen sharing to get to the desktop when I need to. I can't think of a reason as to why yours can't boot without a screen connected. I don't think there's any setting in the BIOS that would prevent it from booting.

It's gonna be tricky to figure out cuz without a screen we don't know whats going on or where it stops booting. Maybe its stuck in the picker? It happens very rarely when I test fresh installs; OpenCore doesn't select any entry and it just sits in the picker waiting. You could also enable the boot chime although I don''t know if there's an internal speaker to play it on and I don't think it's easy to route the audio to the jacks without diving in deeper. Just trying to think of ways to figure out where in the boot process it stops. If the chime sounds we know the OpenCore station was reached.

As a test can you boot with a screen attached and in the picker select your macOS and then press control + enter to set that entry as default? Also for good measure clear NVRAM, maybe something in there is acting up. You could also try removing the connector entries in the config but I doubt that will do anything. I'm not even sure if this has anything to do with OpenCore or macOS.

Can you boot Windows or Linux without a screen attached? I don't think think there's any halting stuff in the BIOS either. Like on my Dell systems many things can cause a "press F1 to continue" when booting. Which is detrimental for headless mode. If you can help me reproduce I can better help out. Let me know which steps you followed and hats different in your setup from mine. Any edits to the config or difference in BIOS settings?

**Comment by antoninchadima** [comment]
I'm using an HDMI Dummy Plug/Headless Ghost/Display Emulator for this purpose. I bought it for 5$ and it has even an HDMI female socket for passthrough.

**Comment by zearp** [comment]
I can't reproduce this. Just booted up a NUC that only has power connected to it and it showed up on my other machines with macOS in Finder under network and I can use screen sharing and move files around just fine. No issues running headless here.

No idea why yours won't boot without a screen. Try loading factory defaults in the BIOS and only change the things mentioned on the repo, also make sure it's not waiting in the picker menu (it can happen sometimes). You can set a default by selecting macOS in the picker and pressing control+enter.

It's tricky to figure out where in the boot process it stops without a screen. Maybe [setting up a boot chime](https://dortania.github.io/OpenCore-Post-Install/cosmetic/gui.html#setting-up-boot-chime-with-audiodxe) can help too, it will sound as soon as OpenCore loads itself. If you feel adventurous you could setup kernel debugging using a serial interface and see if you get any kernel messages, but maybe it doesn't get to the point where it loads the kernel.

Good luck!

**Comment by meienberger** [comment]
Tanks for your answers ! I'll try the headless HDMI. Seems like a wrong config not related to this repo

**Comment by zearp** [comment]
You're welcome, I hope you can sort it out!
