### ISSUE TITLE
OpenCore version mismatch

### ISSUE THREAD

**Issue by KajtekKajtek** [zearp/Nucintosh#143]
Hello

During boot and with terminal I see OpenCore version 0.9.1. But your EFI is 0.9.6 based. Tried reset NVRAM from OC and sudo nvram -d 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version but it didn't help.

NUC8I3BEH with Sonoma and your EFI
What else can I try???

Thank you for help.

**Comment by zearp** [comment]
Resetting nvram should take care of that. Very weird. You can try to delete it manually with the nvram command and reboot. Still odd resetting didn't clear that variable. I don't think any recent config changes did anything in the nvram area as well. Deleting it manually should work though.

**Comment by zearp** [comment]
Yeah really. strange. The only thing I could think of is that maybe it boots from another efi partition somehow? I've left a usb stick in once and my nuc booted from that before the internal disk and it took me a while before I realised it was doing that. I've checked on my freshly installed Sonoma and it seems to work ok for me. Using latest release from the repo.

```
% nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version
4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version	REL-096-2023-10-14
```

**Comment by zearp** [comment]
As a sanity check you could delete everything on your efi partition except your config and copy the latest release to there sans the config too. If the OpenCore picker/menu also shows 0.9.1 then fore sure you're booting using an older version.

**Comment by KajtekKajtek** [comment]
Clean Sonoma install. Disk GPT formated (APFS). Empty EFI. Copied last EFI from github. Changed only serials and deleted nvmefix.kext because I don't need it - SATA SSD. Still shows ver. 0.9.1 :( Maybe new BIOS ver. 095 crash something :( No hope but thank you for your time and help.

**Comment by zearp** [comment]
Normally I would suggest pulling the battery then holding the power button for a bit to drain the board completely. But if I recall correctly it's on the order side of the board and I've broken off those antenna connectors and. Was careful. They are so fragile on the NUCs for some reason. So unless you already got it in a different case you may want think twice pulling the battery. But for sure once thats done it should be gone as those variables are kept in voletile storage. A bit like bios settings.

**Comment by KajtekKajtek** [comment]
Thank you. I will try.

**Comment by KajtekKajtek** [comment]
Done. Battery and drain with power button. Shows OpenCore 0.9.6 now. :):):) Thank  you very much for help.
