### ISSUE TITLE
Sorry for using the issue funtion ;-)

### ISSUE THREAD

**Issue by psykodaddy** [zearp/Nucintosh#147]
Hey there,

I'm pretty desperate and trying to contact you this way :-D

I just got a NUC9i9QNX and made a big mistake: Before updating the BIOS I was changing the IGD option...then this happened:

https://www.intel.com/content/www/us/en/support/articles/000058673/intel-nuc/intel-nuc-kits.html

No POST, just dead because of one damn option  :dodgy: 

Can you help me and give a bin file for this BIOS?

I'll get a new CH341A Programmer and make a dump...can you change this option to default in that dump?

Or is it possible to get a bin out of the cap or bio files from Intel?

Thanks a ,illion for your help!

**Comment by zearp** [comment]
I have totally missed this. Did you manage to sort it out? I may have some ideas!

**Comment by zearp** [comment]
Please do reply if you still need help with this, just closing the issue as it's unrelated to the EFI.
