### ISSUE TITLE
bios url

### ISSUE THREAD

**Issue by andre68723** [zearp/Nucintosh#150]
Hi, 
just for the record - BIOS url (Readme.md) changed  to Asus now https://www.asus.com/de/supportonly/nuc8i5beh/helpdesk_bios/
(have not tried the 095)

**Comment by zearp** [comment]
Thanks! I wouldn't update unless you already lost the ability to undervolt. It got patched at some point (plundervolt) and even when using the bios recovery mode to flash an older version it won't work again. I think the only way to do it is to flash back a full backup made from the bios chip with a chip reader. I lost the ability to on all my NUCs. Unfortunately.
