### ISSUE TITLE
Fix for boot loop after/during 14.4 update

### ISSUE THREAD

**Issue by richtw370** [zearp/Nucintosh#152]
I wanted to suggest an update to the instructions for the 14.4.4 update/install instructions

I too had boot loops and  issues but I finally figured out what to do. 

I got derailed by the secure boot reference.  I looked at my bios setting for secure boot.  I looked at the security settings inside the Apple install tool for secure boot.  I even tried with SIP turned off.  Then I realized you were referring to an additional setting in the config.plist.

The steps that worked for me were

1. Prepare a usb stick with the Sonoma 14.4.4 install
2. Download the latest version of your efi release
3. Make the required updates to identify my nuc
4. Download [AirportItlwm.kext-Sonoma.zip](https://github.com/zearp/Nucintosh/blob/master/Stuff/AirportItlwm.kext-Sonoma.zip) and replace the existingg kext in the efi folder
5. Edit config.plist replace”j174” with “Disabled” in SecureBootModel section:
                           <key>SecureBootModel</key>
   			<string>j174</string>
   			<key>Vault</key>
9. Update the EFI folder on the usb EFI partition with the new EFI data

at this point you should be good to go

**Comment by zearp** [comment]
Thank you! I wanted to write something better and you just did it for me! Apparently putting back the j174 value will work after upgrading but I have not tested it. This whole Apple secure boot thing is a bit odd. Not sure if it had any benefits at all for us. I have it fully working (relevant nvram value returns %2) but I don't see any benefits vs leaving it disabled or set to x86legacy. I've changed the value in the config to the latter after testing an upgrade and full install. We should be ok for now hopefully!

You can see the Apple secure boot level by running this command:
```
nvram 94b73556-2197-4702-82a8-3e1337dafbfb:AppleSecureBootPolicy
```

0 is disabled, 1 is medium security and 2 is full security. But I really don't think it matters at all for a hackintosh. Just use full disk encryption and don't leave anyone alone with your little NUC and it should be ok.

https://dortania.github.io/OpenCore-Post-Install/universal/security/applesecureboot.html

**Comment by zearp** [comment]
Upgraders can also replace the EFI and copy over the serials/mac address/etc before rebooting when doing an OTA update. Or create a fresh 14.4 installer with the latest EFI on it and delete the contents of the internal disk EFI before installing on top of it, or wiping it. I noticed the Disk Utility app doesn't always wipe the EFI when you format a volume/disk.

**Comment by richtw370** [comment]
yes I put back the j174 after upgrade completed and all is working fine!

**Comment by zearp** [comment]
If you want ```2``` all you have to do is generate a 64bit number using Python installed from the Python website as the one bundled with macOs somehow just sucks, also for ProperTree and add it to your config:

Generate the 64bit string:
```
/usr/local/bin/python3 -c 'import secrets; print(secrets.randbits(32))'
```

Reboot into recovery and run this command in the terminal:

```
bless --folder "/Volumes/your_macos_diskname/System/Library/CoreServices" --bootefi --personalize
```

This should do the trick but I have no idea what the benefit would be for us. But it's nice we can achieve the highest level.

**Comment by zearp** [comment]
If you want ```2``` all you have to do is generate a 64bit number using Python installed from the Python website as the one bundled with macOs somehow just sucks, also for ProperTree and add it to your config:

Generate the 64bit string:
```
/usr/local/bin/python3 -c 'import secrets; print(secrets.randbits(64))'
```

Reboot into recovery and run this command in the terminal:

```
bless --folder "/Volumes/your_macos_diskname/System/Library/CoreServices" --bootefi --personalize
```

This should do the trick but I have no idea what the benefit would be for us. But it's nice we can achieve the highest level.

**Comment by zearp** [comment]
I would try the OTA first. I will update my stock NUC in a bit, it's currently doing some tasks what I can't interrupt. I'll post here if the OTA went ok or not. It should be fine now. There were just big changes in 14.4 that are sorted now. Unless you have an urgent need to update I would wait a week before applying it. The people who write OpenCore the drivers and such are quick but not that quick. I also must say that until 14.4 there was *never* any issue that broke stuff. I been doing this NUC build for a years now. I'll post again here as soon as I the NUC is done. I can't update my others as they're on Ventura with Broadcom. They will stay on there as I need iServices to work properly.

**Comment by zearp** [comment]
I would try the OTA first. I will update my stock NUC in a bit, it's currently doing some tasks that I can't interrupt. I'll post here if the OTA went ok or not. It should be fine now. There were just big changes in 14.4 that are sorted now. Unless you have an urgent need to update I would wait a week before applying it. The people who write OpenCore the drivers and such are quick but not that quick. I also must say that until 14.4 there was never any issue that broke stuff. I been doing this NUC build for a years now. I'll post again here as soon as I the NUC is done. I can't update my others as they're on Ventura with Broadcom. They will stay on there as I need iServices to work properly.

**Comment by woody4165** [comment]
As you suggested, I will wait some times, no need to upgrade right now.
Thanks

**Comment by zearp** [comment]
To prevent any surprises set macSO to only check for updates and maybe download them but not install them. My stock NUC is installing the 450mb OTA update now. All seems to be fine. I'm confident Apple didn't change anything big in this update so it should apply just fine. It says 25 minutes to go before it's done. I'll report on a success or fail by that time!

**Comment by zearp** [comment]
No problems applying the 14.4.1 OTA update with the current release EFI.

**Comment by richtw370** [comment]
Upgrade would NOT work if secure boot model was enable in config.plist.  I had to go in and change from j174 to Disabled and then it ran fine
Not sure I will re-enable it at this point

**Comment by zearp** [comment]
No problems here with it set to x86legacy but disabling it shouldn't break anything. I'm pretty sure it is not required to have this enabled for a fully functioning macOS.

**Comment by zearp** [comment]
Updated to 14.5 beta without issues. I hope from here on out Apple stops breaking our stuff 🫠
