### ISSUE TITLE
NUC8I5BEH Opencore won't start

### ISSUE THREAD

**Issue by giorgino-angiolini** [zearp/Nucintosh#159]
Hi,
I'm on NUC8I5BEH, last release as today of your EFI and SONOMA. No change to config file.
Bios setup as per your istructions and last Bios available.
The installation won't start.
Someone can help ?

Thanks in advance !
Giorgio

**Comment by zearp** [comment]
Doesn’t sound like an issue with EFI to me. You also provide barely any information. No steps to reproduce too. 

Do you see the OpenCore menu when booting? If so then you will see a lot if text when booting into the installer. What’s the last message displayed there? 

The issue tracker is to report reproducible reports about bugs in the EFI. I can’t help people figure out how to install macOS.

**Comment by giorgino-angiolini** [comment]
Hi Zearp,
Sorry for the missing infromation you need.
I do not see the OpenCore menu.  Let me try to give you more informaiton with a screenshoot with more debug information (I changed the main opencore file to turn on the debug mode)
![20240703_155457](https://github.com/zearp/Nucintosh/assets/151438331/6ea10508-809b-4715-9796-3abdc91a3953)

**Comment by zearp** [comment]
No errors are shown there. The only thing I can think of is a bios setting being off. I always test the release versions I put on the repo on my stock NUC. I reset the bios and change the settings, wipe nvram and then do a clean install just be sure it works as it should.

Unless you added some hardware or have something plugged in that could cause a stall I really have no idea why it would freeze there. You should also see the menu which you say you didn't see. That is also weird. If you tried another EFI before make sure it's removed and you're booting from the correct EFI. You should see a text menu (picker).

As these are prebuilds the best. I can do is suggest to start fresh and make sure you're booting into the right EFI if you used anything else. The easiest way to do this is to format an old usb stick as FAT32 and just create an EFI folder on there, then press F10 and boot from it.

**Comment by giorgino-angiolini** [comment]
Thanks a lot for your help.
Really appreciate. 
I'll let you know.
Giorgio
