### ISSUE TITLE
USB stick has to be inserted

### ISSUE THREAD

**Issue by aroos** [zearp/Nucintosh#16]
Hi,

I prepared the USB stick as described and was able to install MacOS (Big Sur).
If I remove the USB stick the system doesn't start (no boot device found). Do I've to make an additional step, e.g. copy the EFI folder onto the install drive?

**Comment by aroos** [comment]
Copying the content of EFI folder is enough

**Comment by zearp** [comment]
Somehow I missed this issue. It is mentioned in the last bullet point of the post install section.

```Don't forget to copy the EFI folder from the installer's EFI partition to the internal disk's EFI partition...```

Maybe I need to put some extra emphasis on that part haha.
