### ISSUE TITLE
Question: Does AX210 still present the same issues as other Intel cards?

### ISSUE THREAD

**Issue by naryfa** [zearp/Nucintosh#160]
Hey Zearp,

Found this the other day and was curious if this card, also being an Intel, has the same effect as others in losing some iCloud functionality. The linked article doesn't mention it. Have you checked this before? Perhaps the one that works with NGFF can be used in the same way the old Broadcom can in m.2 slot.

https://github.com/perez987/Intel-AX210-wifi6-on-macOS-Sonoma

**Comment by zearp** [comment]
All NUCs have a soldered on Intel wifi card that works fine in Sonoma. This driver is included in the refi itself. I wouldn't add another Intel card in the m.2 slot but you could if you want dual wireless and add extra antenna's.
