### ISSUE TITLE
Sequoia has been released 

### ISSUE THREAD

**Issue by zearp** [zearp/Nucintosh#161]
For now I don't recommend upgrading unless you like to tinker and try to get things working. Please share your experiences below but please don't expect any support from me just yet. We need certain updates to drivers, mainly wireless and bluetooth.

I would also recommend against install any just released major version on real Macs as it's just very new and lots of things may not work as expected. Specially if you need things like audio drivers, VSTs and other multimedia things. Wait till updates and at least till a .2 has been released before upgrading your stable Sonoma install.

I will keep following the news and track the drivers we need already. As soon as I can I will start testing.

Upgrading to Sonoma 14.7 is fine and won't cause any issues.

**Comment by zearp** [comment]
Going to experiment with the 15.1 beta today. If bluetooth can be made to work we can still use wireless but with the "old" method that doesn't integrate with macOS as nicely and requires a separate app to connect to a network. Which already works fine in Sequoia. But it works if you just want working wireless and don't care about the continuity stuff. Hopefully I can post a test EFI here tonight.

![Screenshot 2024-09-23 at 13 49 55](https://github.com/user-attachments/assets/bc803171-69e3-4d1d-a125-0009ba7da136)

**Comment by zearp** [comment]
A very rough rest EFI here, wireless work when using Heliport. Somehow Heliport is unable to add itself to autostart with the system when selection that option so you have to manually add it to the start-up programmes.

Bluetooth should work but it doesn't. It could be my test machine but I don't think it is. In Sonoma everything works fine. I'll try some more things later.

[Sequoia-test-EFI.zip](https://github.com/user-attachments/files/17101013/Sequoia-test-EFI.zip)

[HeliPort.dmg.zip](https://github.com/user-attachments/files/17101015/HeliPort.dmg.zip)

**Comment by zearp** [comment]
Link to Sequoia beta 4 I use for testing: https://swcdn.apple.com/content/downloads/48/28/062-80466-A_IX9VBQPBBE/8jcyvbnr93ho7qbzvnbw1jv9vtnmo76ifl/InstallAssistant.pkg

**Comment by jqtmviyu** [comment]
Could you share your experience with macOS 14.x?

I'm still using macOS 12.5.7 because many people say it's the last version Apple put serious effort into optimizing for Intel processors.  
However, Homebrew keeps reminding me that they no longer support Monterey, and more and more developers are no longer providing compiled programs for this version.  
Maybe it's time for me to upgrade the system, but I've tried macOS 13.x before, and it had serious heating issues, the settings interface felt more like an iPad, and it was sluggish to respond.

**Comment by zearp** [comment]
I use both Ventura and Sonoma daily without much issues. Seems whatever you experienced has been ironed out, or I didn't run into it.

Apples did change their release schedule to now just be a yearly new major release no matter what and each time they drop support for older stuff. They didn't do that for a long time and used to work much longer on major versions. It is one of the reasons I am moving away from this relentless upgrade schedule. I just need my apps to work. Still using Monterey on my Dell 7020 and I hope Apple will keep giving it security updates though I fear for the worst.

It may be possible to disable those Home Brew nags and just stay on Ventura if that works for you. Don't feel forced to upgrade or think you'll miss out. The few nice stuff like selecting text in images and paste it somewhere was already in Monterey too, as well as good integration with iCloud stuff, specially if you use a Broadcom card.

Depending on your use case it may be interesting to have al look at enterprise linux like RedHat or it's free 1:1 clone Rocky Linux. You get 10 years of security updates and nothing will change in terms of versions, security fixes will be back ported. I use it as a stable base and then run the latest apps inside Flatpaks. But this may not include all the options you and others may need. It is the way to go I think. Free and open source, no spyware, no telemetry, no ads in an OS you paid for like Windows.

Hope this helps you and others lurking 😄

**Comment by zearp** [comment]
New release with working bluetooth and wireless, the latter needs an additional app.

https://github.com/zearp/Nucintosh/releases/tag/v5.4

Closing this now, we'll have to wait for AirportItlwm to be updated to get macOS to see and manage wireless connections. For now this is the best I can do for Sequoia.
