### ISSUE TITLE
USB Type C not working for second monitor

### ISSUE THREAD

**Issue by michaelclaw** [zearp/Nucintosh#162]
Please provide the follow information:

- Steps to reproduce the issue -- this is crucial
Fresh install and finish following your guide then plugging in a type c to hdmi cable into the NUC8

- macOS version and optionally the build number
Sonoma 14.7 | Latest EFI from your Github

- Any changes you made to the config and/or EFI other than serials/etc
Zero changes than what's in your guide

- Any logs related to the issue if applicable
Not sure how to pull the logs for this.

**Comment by michaelclaw** [comment]
So I had closed the issue earlier cause I hadn't rebooted the NUC yet but that had fixed it and I had the second display working with the USB c to hdmi working. The nuc had a random complete shutdown a couple hours later (2x so far) and since then the second display hasn't worked. I ordered the cable just for this so here is the link. https://www.amazon.com/dp/B083Z8QBJ5?ref=ppx_yo2ov_dt_b_fed_asin_title&th=1

I'm not sure exactly what is causing the complete shutdown cause I just bought the unit and immediately installed hackintosh.

**Comment by michaelclaw** [comment]
**update**

I was able to get the second screen working again but unplugging and replugging back in multiple times and it activated the second screen so I'm not sure what is happening. Is there any logs I could check for the full system shutdowns though?

**Comment by zearp** [comment]
I would try the same on another operating system. Hot plugging screens is not something macOS really likes, same issue on my Macbooks. If you have every connected before pouring up it should be fine. I always test with a usb-c to dp cable + cdmi for dual screens and have also tested those hdmi ports on the usb-c hub, no problems there either. 


Just hot plugging isn't always working properly. I would try in another OS and also another cable if you have one. As weird as it sound when I setup the Dell 7020s and spend an awful lot of time trying to get 2-3 screens working on it we found out that cables do matter and a cable that works fine in Windows or Linux might not work fine on macOS. It is just one those quirks of running a hackintosh.

I hope your testing can lead a cause and fix. For me it's difficult to help if I can't reproduce it here. Just to double check you're just using a stock NUC right? No Broadcom or other pci devices? I can do a fresh Sonoma install on my test NUC that I always format and redo. It's running Sequoia now, trying to get bt to work. Sorry I can't do much more.
