### ISSUE TITLE
Connector for NUC8

### ISSUE THREAD

**Issue by DANDEBAND** [zearp/Nucintosh#163]
Good afternoon, I would need help with the connector for the type of port that I indicate in the photo. I tried to search on Amazon and other sites but I can't find it.... could you send me the link to buy that type of connector.
my computer is a NUC8 model
I ordered one but it is different and placed backwards
I have the BCM94360CD card for the macOS Sequoia for wireless function.
Thanks

![scheda per wifi](https://github.com/user-attachments/assets/6b3bbd4d-6f80-4218-a767-5118531c4390)

**Comment by zearp** [comment]
Do not put it there! The connector on the converter card is not the correct type. It is a usb port and needs to go on one of the two tiny usb connectors. I think those are the smallest jst plugs (1.25mm) but I'll have to double check.

The connector you're trying to connect to is for something else. N + M are the two internal usb ports the card needs to connect to. If you can solder it wouldn't be too difficult to adapt it. 

![Screenshot 2024-10-07 at 01 56 36](https://github.com/user-attachments/assets/e9c99798-3f27-478e-bebd-dc7d98f6f241)

Mind you to have working Broadcom ins Sequoia you'll need to use OCLP, I don't support or use that myself becasue a lot of security features have to be disabled. But you can use it and still get most of the iCloud integration things. With Intel only some works. Like hand-off.

There (used) to sell converter boards made for the NUC with the small connector on the end already. See this picture on the repo: https://raw.githubusercontent.com/zearp/Nucintosh/refs/heads/master/Stuff/NUC8-m2adapter.jpg

Good luck and let me know how it went!

**Comment by zearp** [comment]
I looked it up and the other connector is for a front panel, like hdd led. I am not sure if all the card needs is voltage, maybe it takes 5 volts from there but I was under the impression it also needs a usb connection for the bluetooth part, the wifi part goes over m2.

![Screenshot 2024-10-07 at 02 04 09](https://github.com/user-attachments/assets/f4f98379-3014-4af4-835a-bd685a2fa7d0)

Bad things could happen if you just plug it in and send 5 volts into the convertor. It might break both the converter bored and your Broadcom card. Please double check if the 5 volt pins match up and the data lines are not needed.

**Comment by durix75** [comment]
Hi,
I bought this one and is fully functional with my nuc
Just found this amazing item on AliExpress. Check it out! 20,32€ | Black BCM94360CS2 Network Card to M Key PCIe X4 M.2 NGFF Adapter Card Dedicated to NUC8
https://a.aliexpress.com/_mreSu0Y

**Comment by zearp** [comment]
Thanks for sharing! I edited the spammy text that Ali Express adds when you use the share option. Thanks for sharing though! I'm glad they're still sold and will order a backup just in case 😅

**Comment by DANDEBAND** [comment]
Good evening I ordered the card that you recommended to me on the AliExpress website thanks for your support.

**Comment by DANDEBAND** [comment]
Good evening
I received the Wifi converter card
Broadcom finally works 100%
Working Wireless, Bluetooth and also Airdrop all complete excellent!
thanks for your collaboration
now I attach the photo

**Comment by DANDEBAND** [comment]
Good evening
I received the Wifi converter card
Broadcom finally works 100%
Working Wireless, Bluetooth and also Airdrop all complete excellent!
thanks for your collaboration
now I attach the photo
![IMG_4756](https://github.com/user-attachments/assets/e8a353ba-3ebe-4dfe-baa3-8e1fd13cbe6e)
<img width="929" alt="Screenshot 2024-10-23 alle 21 05 39" src="https://github.com/user-attachments/assets/8fb40fdd-b3e3-4b11-9d72-ef33c975872a">

**Comment by zearp** [comment]
Very nice! If you do not need disk encryption or full SIP/filesystem sealing you can use OCLP to patch Sequoia post-install and get everything to work natively in there too. I personally do not like giving up on those things but I know not everybody shares that opinion.
