### ISSUE TITLE
Postinstall failure

### ISSUE THREAD

**Issue by stschulze1972** [zearp/Nucintosh#20]
NUCmini ~ % sudo mount -uw / && killall Finder && sudo mv /System/Library/CoreServices/Menu\ Extras/ExpressCard.menu /System/Library/CoreServices/Menu\ Extras/ExpressCard.menu.bak && sudo touch /System/Library/CoreServices/Menu\ Extras/ExpressCard.menu
Password:
mount_apfs: volume could not be mounted: Permission denied
mount: / failed with 66
NUCmini ~ %

**Comment by zearp** [comment]
Big Sur I assume? See last bullet point [here](https://github.com/zearp/Nucintosh#big-sur).

**Comment by zearp** [comment]
Big Sur I assume? See last bullet point [here](https://github.com/zearp/Nucintosh#big-sur). Also make sure SIP is fully disabled before running the command. On Big Sur you need to set ```csr-active-config``` to ```FF0F0000```. Don't forget to turn SIP back on once you've hidden the icon.

**Comment by zearp** [comment]
Big Sur I assume? See the last bullet point [here](https://github.com/zearp/Nucintosh#big-sur). Also make sure SIP is fully disabled before running the command. It's disabled by default in my config for Catalina and older. On Big Sur you need to set ```csr-active-config``` to ```FF0F0000```. Don't forget to turn it back on once you've hidden the icon.

**Comment by zearp** [comment]
I've tried with 11.1 and deleting snapshots has been tightened down to the point deleting snapshots no longer works without jumping trough a lot of hoops. If I can find a more friendly method I will share it, for now the easiest way to hide the icon is with a cool little utility called [Hidden Bar](https://github.com/dwarvesf/hidden).

**Comment by peking84** [comment]
I was running around some circles in the past few weeks and also had issue on NUC8i5 with Big Sur 11.1 and i just bumped to your reported issue while digging for PCI device assignments...

Here is what i managed to get working:


Set Opencore config.plist : Disable SIP System Integrity Protection
 csr-active-config to FF0F0000

Reboot to recovery mode, mount (not the Data one) to RW
 mount -uw /Volumes/macOS 

Make a snapshot to restore if something wents wrong
 /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs_systemsnapshot -s "ExpressMenu_before" -v /Volumes/macOS

Make the change
 cd /Volumes/macOS/System/Library/CoreServices/Menu\ Extras/
 mv ExpressCard.menu ExpressCard.menu.backup 
 touch ExpressCard.menu

Create new snapshot and make it bootable
 /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs_systemsnapshot -s "macOS Big Sur" -v /Volumes/macOS
 /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs_systemsnapshot -r "macOS Big Sur" -v /Volumes/macOS

Restore config.plist parameter 
 csr-active-config to 00000000 (Enable SIP System Integrity Protection)

cheers

**Comment by zearp** [comment]
@peking84 That's pretty much the only method thats left but I don't really wanna advocate it cuz it's too convoluted for such a small tweak. If only Apple would allow us to permanently remove icons normally. You can drag icons out by holding down command (or windows key) but they come back on next reboot. Makes me wonder if it's something they forgot to take it out or if it's designed to only hide icons until the next boot.

I'm thinking to add a section explaining how to install without sealing the filesystem, the Big Sur micro patchers uses that and I think you can seal it again once you made your changes. I like having full access to the filesystem but I also like the security idea behind it. Ideally Apple would add another csr flag, like authenticated-root but for full access to your filesystem. That way we don't have to mess with snapshots at all.

For now I've settled using Hidden Bar, quite like it. I'm hiding pretty much all icons for a clean look.

![Screenshot 2021-01-07 at 03 35 16](https://user-images.githubusercontent.com/63272687/103844084-6d5d9500-5099-11eb-9743-5b3a107af592.png)

![Screenshot 2021-01-07 at 03 35 23](https://user-images.githubusercontent.com/63272687/103844081-6c2c6800-5099-11eb-9e24-fc640107597a.png)

**Comment by zearp** [comment]
Closing this for now, will add any new info/solutions to the repo. Hopefully someone can develop a little utility that makes these kind of things easier. It beyond silly we have to mess with snapshots to get full access to the filesystem.
