### ISSUE TITLE
Updating to 11.2.2 NUC no longer boots

### ISSUE THREAD

**Issue by superchief** [zearp/Nucintosh#30]
I'm not sure if this is from boot-loader or from something like Lulu (not Lilu). I tried disabling Lulu from Catalina (dual boot), but it Big Sur would no longer boot after either way.

I'm looking to see how others fare.

**Comment by zearp** [comment]
It might be sealing your filesystem; when you upgrade or clean install Big Sur at some point it will seem to have stalled/crashed but it is in fact sealing the filesystem, which can take a very long time if you have a lot of data. What is shown on screen in verbose boot?

You can try installing Big Sur on top of it, it won't delete any of your apps or settings. Or alternatively, do a clean install to another disk and in then import your data and settings from the old disk that doesn't boot. You can install to an external disk or put the non-booting disk in a usb case and use it when importing back your stuff.

To me it doesn't sound like an issue with the EFI itself so I'll close the issue as this isn't really the best place to find help, other than suggestions by me haha. But feel free to update here and let me know how it went, shouldn't be too hard to sort this out. I don't think it's possible for Lulu (the firewall frontend) to mess with the boot process.

Good luck!

**Comment by superchief** [comment]
This happens after the verbose part. It gets pretty far into the boot process and stops. I waited over an hour and then pulled the plug. I can try it on a fresh install after I Time Machine everything back (I'll do a dual boot), but my guess is something is up.
