### ISSUE TITLE
Exact Opencore Release Number for  Nucintosh 1.6 Release

### ISSUE THREAD

**Issue by gtrooper** [zearp/Nucintosh#33]
Hello, on your 1.6 Nucintosh release you uploaded an EFI folder with the following name.

Stable EFI (14022021)

Could you please let me know THE EXACT Beta Release you used from the following link ?

https://dortania.github.io/builds/?product=OpenCorePkg&viewall=true

I need to extract some files from the original build as USING mismatched individual files had caused many issues in the past ! Thank you !

**Comment by zearp** [comment]
There's no beta release I use, everything is build from source. Your best bet would be a build form the same day, if the day had multiple commits then you'll have to try them all. 

You can run ```nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version``` and see what that returns but I don't think it includes any version info beyond the basics.

Why would you need this though? Just use the snapshot you need and move back kext and config or manually replace only the BOOT and driver folder and OpenCore binary. That way no versions will be mixed up.

**Comment by gtrooper** [comment]
Oh, I am not sure I fully understand your answer. So, what I basically need to do is ADD OpenCanopy.efi to your latest 1.7 release AND your 1.6 release. Last time I tried to do the same on a release you created on December 2020 I used this site https://github.com/williambj1/OpenCore-Factory  to find the exact Opencore release and I managed to find the one you have used. But now it is discontinued. I had some issues in the past while trying to extract OpenCanopy.efi from the latest release and copy it manually to a previous one for various reasons. So what is the best path for me here ? I just want to add some Beauty Treatment ! Also, in the next 2 weeks I will also have an answer regarding how well some thunderbolt devices work. Thanks for your amazing work !

**Comment by zearp** [comment]
Ah, thats not too difficult.

- Download and extract an OpenCore snapshot from [here](https://github.com/dortania/build-repo/releases/download/OpenCorePkg-1ed6e7d/OpenCore-0.6.8-RELEASE.zip)
- Inside the X64 folder you will find an EFI folder
- From the EFI folder copy the BOOT folder to your EFI, replacing the current one
- From the OC folder copy OpenCore.efi to the OC folder of your EFI, replacing the current one
- From the OC/driver folder copy OpenRuntime.efi + OpenCanopy.efi to your EFIs OC/driver folder replacing OpenRuntime.efi

Thats all thats needed. 

I've thought about adding OpenCanopy + a small theme but leave it disabled by default, it's important to know whats going on when setting things up (verbose boot and such). But once things run you can hide the picker menu and add a nice theme. You can hold down alt or escape to get in the OpenCore menu again. I personally don't bother with it cuz I rarely reboot and just run macOS as my only OS.

You'll also have to add in some resources before any themes will work, and change the config too. In case you're unfamiliar with it there is a guide here: https://dortania.github.io/OpenCore-Post-Install/cosmetic/gui.html

Thunderbolt hot plugging works with [patched firmware](https://github.com/zearp/Nucintosh/blob/master/Stuff/Tb3Patch.md) but it currently breaks waking up from sleep. Other than that Thunderbolt should work fine. If you don't need to hotplug often it shouldn't be an issue to not patch and have working sleep. There's also a tiny chance patching the firmware fails, it happened once in my testing but I flashed dozens of times. Hopefully this can be fixed, if not I will revert back to old ACPI patches as they worked fine just no hotplug either.

**Comment by iNuc-Pro** [comment]
> Thunderbolt hot plugging works with [patched firmware](https://github.com/zearp/Nucintosh/blob/master/Stuff/Tb3Patch.md) but it currently breaks waking up from sleep. Other than that Thunderbolt should work fine. If you don't need to hotplug often it shouldn't be an issue to not patch and have working sleep. There's also a tiny chance patching the firmware fails, it happened once in my testing but I flashed dozens of times. Hopefully this can be fixed, if not I will revert back to old ACPI patches as they worked fine just no hotplug either.

Wow that extensive just for the hot plugging. I mean hot plugging is for portable TB3 device like external TB3 SSD which require to plug and unplug while the windows/ MacOS still running right? Other TB3 devices like display and eGPU which always stay connected to the NUC, do not need this patching and the eGPU still works on both windows / MacOS. Correct?

**Comment by zearp** [comment]
@iNuc-Pro thats correct.
