### ISSUE TITLE
Ask for advice! thunderbolt3 hot plug problem!

### ISSUE THREAD

**Issue by frozenzero123** [zearp/Nucintosh#40]
I have no plan to change the firmware for the time being, but I found that the current hot patch cannot be inserted into the docking station after booting to realize the USB3.0 rate can only be connected to 2.0, but when the USB-c device is plugged in before booting, it can be used after booting. Normally recognized, if you can use the full-featured type-c alone, I think it may not be an option to implement the hot-swappable function here.

**Comment by zearp** [comment]
Hot plugging for Thunderbolt devices will not work without patching but hot plugging usb-c devices will work. Thunderbolt devices need to be plugged in before booting into macOS, all Thunderbolt devices including eGPU should work. Are you use Thunderbolt or usb-c devices? Thunderbolt uses usb-c connections but is not the same.

It is important to differentiate when reporting an issue, else its hard for me to know where to look for things that might cause the issue you face. 

I'm not sure if I understand what you mean with usb 3 rate can only be connected to 2. Please describe in more details and also describe the steps needed to reproduce this.

For now please try [this](https://github.com/zearp/Nucintosh/files/6264553/EFI-test.zip) EFI which uses the previous ACPI patches relating to usb-c/Thunderbolt. Let me know how it worked out.

**Comment by frozenzero123** [comment]
1. The efi you gave me can work (full-featured type-c)
2. If the firmware is not refreshed, if the Thunderbolt interface is not plugged into the boot, it can only recognize the usb2.0 signal at this time, but plug in the Thunderbolt device (or full-function type-c) before booting, and it can work normally. The request I made before means that I hope to be able to do three different options, such as supporting only full-featured type-c (just like the efi you gave me), Thunderbolt hot-plugging, or non-hot-plugging!

**Comment by zearp** [comment]
Ah thanks, I get it now!

With the EFI posted Thunderbolt will work fine but only if it's connected before starting macOS. The only Thunderboltk device I can think of that would benefit form hotplug are storage devices. I mostly use Thunderbolt for docks and eGPU.

I will revert back to the older ACPI patches, losing usb-c functionality is not good and the firmware hotplug patch currently breaks sleep as well.

Not sure if I'm able to get Thunderbolt hotplug + sleep + all usb-c functionality to work. It requires in depth knowledge of ACPI and firmware patching that I don't possess 😅

Just for clarity point 2 is in regard to the EFI posted here or the one from the repo?

**Comment by zearp** [comment]
Just tested a usb3 flash drive using the usb-c port and it works in 5gb/s mode. It wasn't connected on boot. Just hotplug using the EFI posted in here. I have no Thunderbolt 3 devices to try here only 2, but these patches were confirmed working by several people.

Hopefully I have some time to try and sort out the usb-c speeds using the current repo but if I can't the ACPI patches will be reverted to the old style where everything except Thunderbolt hotplug work perfectly fine.

**Comment by zearp** [comment]
Reverted back to how things were, will setup a tets branch for TB3 stuff in due time.

https://github.com/zearp/Nucintosh/pull/41

I consider this closed now, do let me know if you have other issues though. I should've tested these TB3 patches a lot better before adding them to master. Lessons were learned 😅
