### ISSUE TITLE
NUC8i5

### ISSUE THREAD

**Issue by wem2017** [zearp/Nucintosh#45]
Thanks for your repo, this is perfect

- I checkout lasted master branch, I see some fix for another device, I have some question:
1. This repo only support and target stable Hackintosh NUC8?
2. Previous month I have an issue with OCB: StartImage failed when booting only MacOS SSD Samsung 970 Evo plus

![image](https://user-images.githubusercontent.com/58833808/119213562-389f2700-baea-11eb-970d-4e9cf1346beb.png)

Thanks

**Comment by zearp** [comment]
This repo is for Coffee Lake NUC8 models only. 

Those config entries are two default entries needed for the validation tool to give no errors. Both are disabled. 

I’m not sure what happened with your boot.  Not sure what causes the start image error. If your disk is NVMe you can disabling the fix up kext for those drives. But if it happened once maybe it was something from nvram or bios. 

If you can reproduce it and give me the steps to take so I can test here and see if I also run into it, I can try to fix it. If it happens again take down as much info as you can like error messages and relevant logs in addition to the steps needed to reproduce it. 

There is some functionality in OpenCore that can make sure other operating systems can’t mess up the boot but I have that disabled by default. Check the section called ‘’’ LauncherOption’’’ in the documentation: https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf

It’s most likely not relevant to your issue but can prevent boot issues if you run multiple operating systems.

**Comment by zearp** [comment]
Looked up the error you got. Found this about it in the Dortania guide:

> This is due to OpenCore getting confused when trying to boot Windows and accidentally thinking it's booting OpenCore. This can be avoided by either move Windows to it's own drive or adding a custom drive path under BlessOverride. 

Another option you can try to prevent it although if you set things up correctly it shouldn't happen, that is using a separate disk for each operating system and booting into them using your BIOS menu.

While OpenCore can boot other operating systems, it may inject some properties and apply APCI patches that could lead to issues. I have most if not all ACPI patches set to only apply when booting macOS but I wouldn't boot Windows from OpenCore *unless* you use BootCamp. Like on a real Mac.

For Linux it shouldn't be much of an issue but I'd still recommend using your BIOS boot menu just to be sure nothing that shouldn't be appleid is applied. I see OpenCore as took to transform your machine into a Mac for all intents and purposes. So if you want to run Windows, use BootCamp and install it. It will work great with OpenCore. A normal Windows install might not work so good when booted from OpenCore.

I might look into enabling some kind of boot protections but they shouldn't be needed when managing your system properly. As a rule of thumb try to keep every operating system on it's own drive and when installing them disconnect other disks so the EFI partitions of other operating systems won't be modified by installers. Then always boot into them from the BIOS boot menu, this will prevent pretty much all issues.

Hope this helps. I'll close this issue now as I don't think there's a problem with the EFI.

**Comment by zearp** [comment]
Why do I even bother putting time in responding to open issues when people that open them can’t be bothered to reply anyone. Wasting my time.
