### ISSUE TITLE
New BIOS update - May 10, 2021

### ISSUE THREAD

**Issue by superchief** [zearp/Nucintosh#46]
No issue other than wanted I to know if tried the new 0088 BIOS update?

It says this in the release notes:
Known Errata: Due to the Intel® ME firmware update in BIOS version 0088, you can’t downgrade to version 0087or earlier

The only thing I can say is that your last OC update, Stable EFI (03052021), caused all sorts of issues for me.
I went back to using Stable EFI (13042021) and she's running great. I haven't tried the latest one.

**Comment by zearp** [comment]
I haven't checked out the new bios yet, should be ok to upgrade I think. Unlikely things will be added/removed that mess with macOS at this point. I'm surprised Intel still updates it!

What kind of issues did you experience? I'm using the current repo on my own NUCs and haven't ran into issues. I don't know what areas you had issues in and what kind. I did disable a now deprecated frame buffer setting, but that should solve issues not create them haha. 

Curious to what you experienced.

**Comment by zearp** [comment]
Updated the bios and all seems fine including undervolting. Nothing in the change log that would cause issue. I'd say its safe to upgrade and probably will be in the future too.

**Comment by zearp** [comment]
Would be nice if people that open issues only do so if they plan to respond to them. You said you had lots of issues but didn’t explain which ones. Why open an issue if you can’t be bothered to reply? Smh.
