### ISSUE TITLE
Sleep bluetooth

### ISSUE THREAD

**Issue by Kruglianin** [zearp/Nucintosh#48]
Hello.
The guide says:
"One last thing to remember is that waking the machine from sleep using bluetooth devices will not work. This is due to power being cut to the module. "
Does this also apply to original modules from Apple?
Or just third parties?
Thanks in advance.

**Comment by zearp** [comment]
Yes it does. This is not due to software. During sleep power to the module is cut. The only way to  make it work is by modifying your adapter card.

**Comment by zearp** [comment]
It applies to any module in the m.2 slot. This is not due to software. During sleep power to the module is cut. The only way to  make it work is by modifying your adapter card so the Bluetooth module isn’t powered down.
