### ISSUE TITLE
NVME controller randomly locking shutdowns and generating slowdowns

### ISSUE THREAD

**Issue by cangurellobello** [zearp/Nucintosh#53]
Please provide the follow information:

- Steps to reproduce the issue
  Mount latest EFI; Shutdown the os or set heavy load
- macOS version and optionally the build number
  BigSur 11.4 20F71
- Any changes you made to the config and/or EFI other than serials/etc
  Removed std verbose and installed latest kexts from official repos (See log)
- Any logs related to the issue if applicable
```
panic(cpu 0 caller 0xffffff80044ce860): nvme: "Fatal error occurred. CSTS=0xffffffff US[1]=0x0 US[0]=0xed VID=0x8086 DID=0xf1a5
. FW Revision= PSF121C\n"com.apple./System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-557.120.1/Common/IONVMeController.cpp:5499
Backtrace (CPU 0), Frame : Return Address
0xffffffb0801cba70 : 0xffffff8001c8e0dd 
0xffffffb0801cbac0 : 0xffffff8001dd4f33 
0xffffffb0801cbb00 : 0xffffff8001dc552a 
0xffffffb0801cbb50 : 0xffffff8001c32a2f 
0xffffffb0801cbb70 : 0xffffff8001c8d8fd 
0xffffffb0801cbc90 : 0xffffff8001c8dbf3 
0xffffffb0801cbd00 : 0xffffff800249d81a 
0xffffffb0801cbd70 : 0xffffff80044ce860 
0xffffffb0801cbd90 : 0xffffff80044b345b 
0xffffffb0801cbef0 : 0xffffff80044b363e 
0xffffffb0801cbf30 : 0xffffff80024684ee 
0xffffffb0801cbf70 : 0xffffff8002468212 
0xffffffb0801cbfa0 : 0xffffff8001c3213e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[38BC0D0C-B305-30F6-8A8D-6804830F891A]com.apple.0xffffff80044ac000-com.apple.driver.0xffffff80044d5fff
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[423BF733-A622-3BC9-8F0F-920A2927CD35]com.apple.0xffffff80030fe000-com.apple.driver.0xffffff8003107fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[366C7BD4-9502-3D1C-ABBE-DE9749913D0C]com.apple.0xffffff80032c0000-com.apple.driver.0xffffff80032d5fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[99A70889-A31C-3B25-8E88-ADD3F317E4E4]com.apple.0xffffff800476a000-com.apple.driver.0xffffff8004792fff
            dependency: com.apple.iokit.IOReportFamily(47)[367CCAE7-DAB4-3424-B191-44044619D5CB]com.apple.0xffffff80047a1000-com.apple.driver.0xffffff80047a3fff
            dependency: com.apple.iokit.IOStorageFamily(2.1)[A0D72FE9-649B-316A-8B5C-934E295FF0B5]com.apple.0xffffff800486d000-com.apple.driver.0xffffff800487efff

Process name corresponding to current thread: kernel_task
Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
20F71

Kernel version:
Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
Kernel UUID: 52A1E876-863E-38E3-AC80-09BBAB13B752
KernelCache slide: 0x0000000001a00000
KernelCache base:  0xffffff8001c00000
Kernel slide:      0x0000000001a10000
Kernel text base:  0xffffff8001c10000
__HIB  text base: 0xffffff8001b00000
System model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)
System shutdown begun: YES
Panic diags file available: NO (0xe00002cd)
Hibernation exit count: 0

System uptime in nanoseconds: 3289511353448
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000002fde627dfd9
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000000731df97c4 0x0000000000000000
last started kext at 2638974510228: com.apple.filesystems.msdosfs	1.10 (addr 0xffffff7f9d4ad000, size 57344)
last stopped kext at 414877878229: com.apple.driver.AppleFIVRDriver	4.1.0 (addr 0xffffff7f9b24b000, size 8192)


loaded kexts:
com.zxystd.IntelBluetoothFirmware	2.0.0
com.zxystd.AirportItlwm	2.0.0
as.acidanthera.mieze.IntelMausi	1.0.7
ru.joedm.SMCSuperIO	1.2.4
as.vit9696.SMCProcessor	1.2.4
as.vit9696.VirtualSMC	1.2.4
as.vit9696.WhateverGreen	1.5.0
org.acidanthera.NVMeFix	1.0.9
org.vanilla.driver.CPUFriend	1.2.3
as.vit9696.AppleALC	1.6.1
as.vit9696.Lilu	1.5.3
com.apple.filesystems.msdosfs	1.10
com.apple.driver.AudioAUUC	1.70
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.AGPM	122.1
com.apple.driver.X86PlatformShim	1.0.0
com.apple.fileutil	20.036.15
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleUpstreamUserClient	3.6.8
com.apple.driver.AppleMCCSControl	1.14
com.apple.driver.AppleHDA	283.15
com.apple.driver.AppleIntelKBLGraphics	16.0.4
com.apple.driver.AppleGraphicsDevicePolicy	6.3.3
com.apple.AGDCPluginDisplayMetrics	6.3.3
com.apple.driver.pmtelemetry	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.usb.AppleUSBUserHCI	1
com.apple.iokit.IOBluetoothSerialManager	8.0.5d7
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHV	1
com.apple.driver.AppleDiskImages2	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleIntelCFLGraphicsFramebuffer	16.0.4
com.apple.driver.AppleIntelPCHPMC	2.0.1
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.filesystems.tmpfs	1
com.apple.filesystems.hfs.kext	556.100.11
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.filesystems.apfs	1677.120.9
com.apple.private.KextAudit	1.0
com.apple.driver.AppleAHCIPort	346.100.2
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleAPIC	1.7
com.apple.AppleSystemPolicy	2.0.0
com.apple.nke.applicationfirewall	311
com.apple.iokit.IOKitRegistryCompatibility	1
com.apple.iokit.EndpointSecurity	1
com.apple.kext.triggers	1.0
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.driver.DspFuncLib	283.15
com.apple.kext.OSvKernDSPLib	529
com.apple.driver.AppleGraphicsControl	6.3.3
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.iokit.IOSerialFamily	11
com.apple.iokit.IOAVBFamily	940.4
com.apple.plugin.IOgPTPPlugin	985.2
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.driver.AppleHDAController	283.15
com.apple.iokit.IOHDAFamily	283.15
com.apple.iokit.IONDRVSupport	585.1
com.apple.iokit.IOAudioFamily	300.6.1
com.apple.vecLib.kext	1.2.0
com.apple.AppleGPUWrangler	6.3.3
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOAcceleratorFamily2	442.9
com.apple.AppleGraphicsDeviceControl	6.3.3
com.apple.iokit.IOGraphicsFamily	585.1
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	8.0.5d7
com.apple.iokit.IOBluetoothHostControllerUSBTransport	8.0.5d7
com.apple.iokit.IOBluetoothHostControllerTransport	8.0.5d7
com.apple.driver.AppleUSBMergeNub	900.4.2
com.apple.driver.AppleBSDKextStarter	3
com.apple.iokit.IOSurface	290.8.1
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleXsanScheme	3
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.2
com.apple.driver.AppleIntelLpssI2C	3.0.60
com.apple.iokit.IO80211Family	1200.12.2b1
com.apple.iokit.IOSkywalkFamily	1
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.corecapture	1.0.4
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.AppleEFINVRAM	2.1
com.apple.iokit.IOAHCIFamily	294.100.1
com.apple.driver.AppleIntelLpssGspi	3.0.60
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOSMBusFamily	1.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.security.AppleImage4	3.0.0
com.apple.iokit.IOTimeSyncFamily	985.2
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.DiskImages	493.0.0
com.apple.iokit.IOBluetoothFamily	8.0.5d7
com.apple.iokit.IOReportFamily	47
com.apple.iokit.IOBluetoothPacketLogger	8.0.5d7
com.apple.security.quarantine	4
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.iokit.CoreAnalyticsFamily	1
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	511.120.2
com.apple.iokit.IOUSBMassStorageDriver	184.121.1
com.apple.iokit.IOSCSIBlockCommandsDevice	436.121.1
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOSCSIArchitectureModelFamily	436.121.1
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.kext.CoreTrust	1
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.driver.watchdog	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	11.1
com.apple.kec.Libm	1
```

**Comment by zearp** [comment]
Does it happens with NVMeFix.kext both enabled and disabled?
What brand/model NVMe do you use?
Does it happen with kexts used on the repo?

I need to have an identical EFI as yours, specially the kexts. Cuz I might be a few commis behind in regards to the kexts you use. Unlikely that would be an issue but I rather use the exact same kexts.

I've got some Crucial and Corsair ones and didn't experience any issues with them. I did a few shutdowns on my test NUC just now that has a Crucial in there, no panics. How can I reproduce the load that causes it? Maybe that can trigger the panic.

**Comment by zearp** [comment]
- Does it happen with NVMeFix.kext both enabled and disabled?
- What brand/model NVMe do you use?
- Does it happen with kexts used on the repo?

I need to have an identical EFI as yours, specially the kexts. Cuz I might be a few commis behind in regards to the kexts you use. Unlikely that would be an issue but I rather use the exact same kexts.

I've got some Crucial and Corsair ones and didn't experience any issues with them. I did a few shutdowns on my test NUC just now that has a Crucial in there, no panics. How can I reproduce the load that causes it? Maybe that can trigger the panic.

**Comment by zearp** [comment]
Just noticed you downgraded kexts, not upgraded them. I'm compiling everything from source based on the current sources. Like AppleALC and others are one version ahead of yours. If you download release version form the official repo's you will have older versions. If you must change the kexts yourself (I don't understand why) then use [Dortania builds](https://dortania.github.io/builds/), they have the latest builds based on the latest sources like I do.

Weird things can happen when you run "older" kexts and newer kexts and a newer/older OpenCore build together as they interact a lot with each other. Most kexts we use are made by the same team of people. You can't just upgrade or downgrade one or two kexts without also doing the rest. Some newer function or bug fix may depend on other kexts being up to date too.

Please try the the release from the repo so I can use that release too and we're sure to use the same stuff when trying to reproduce.

**Comment by zearp** [comment]
Just noticed you downgraded kexts, not upgraded them.

I'm compiling everything from source based on the current sources. Like AppleALC and others are one version ahead of yours. When you download release version from the official repo's you will have older versions. If you must change the kexts yourself (I don't understand why) then use [Dortania builds](https://dortania.github.io/builds/), they have the latest builds based on the latest sources like I do. Or, replace everything with release builds. Don't mix it up.

Weird things can happen when you run older kexts and newer kexts and a newer/older OpenCore build together as they interact a lot with each other. Most kexts we use are made by the same team of people. You can't just upgrade or downgrade one or two kexts without also doing the rest. Some newer function or bug fix may depend on other kexts being up to date too.

Please try the the release from the repo so I can use that release too and we're sure to use the same stuff when trying to reproduce.

**Comment by zearp** [comment]
Just noticed you downgraded kexts, not upgraded them.

I'm compiling everything from source based on the current sources. Like AppleALC and others are one version ahead of yours. When you download a release version from the official repo's you will get older versions compared to a release here. If you must change the kexts yourself (I don't understand why) then use [Dortania builds](https://dortania.github.io/builds/), they have the latest builds based on the latest sources like I do. Or, replace everything with release builds. Don't mix it up.

Weird things can happen when you run older kexts and newer kexts and a newer/older OpenCore build together as they interact a lot with each other. Most kexts we use are made by the same team of people. You can't just upgrade or downgrade one or two kexts without also doing the rest. Some newer function or bug fix may depend on other kexts being up to date too.

Please try the release from the repo so I can use that release too and we're sure to use the same stuff when trying to reproduce.

**Comment by cangurellobello** [comment]
> * Does it happen with NVMeFix.kext both enabled and disabled?
Enabled
> * What brand/model NVMe do you use?
INTEL SSDPEKKW128G7; Lexar Professional NM700
> * Does it happen with kexts used on the repo?
Yes
> 
> I need to have an identical EFI as yours, specially the kexts. Cuz I might be a few commits behind in regards to the kexts you use. Unlikely that would be an issue but I rather use the exact same kexts.
[EFI.zip](https://github.com/zearp/Nucintosh/files/6758788/EFI.zip) 
> Please try the release from the repo so I can use that release too and we're sure to use the same stuff when trying to reproduce.
> 
It happens with the latests repo EFI too, I noticed that CPU usage gets really high too just scrolling on web content on Safari.
I'm a newbie to OpenCore I didn't know drivers could interfere with the config.

**Comment by cangurellobello** [comment]
Is there any way to get a system trace while logged in?

**Comment by zearp** [comment]
Not sure if I understand correctly, but if it doesn't happen with the fix-up kext disabled you can leave it disabled.

Your Intel 600p is on the known troublemakers list: https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/Storage.html -- removing it or disabling it in ACPI might be the only way to stop the panics.

If you can panics with it enabled and disabled then I'm afraid there's nothing to be done.  Here's an issue with a very similar panic to you: https://github.com/acidanthera/bugtracker/issues/1286

Bot sure if it can be fixed but the ticket suggests they would need a drive to test with themselves. If you'd want to collect logs you'll need to download a debug version of the kext from their repo or Dortania site. But it might not be enough for the programmers to fix things.

NVMeFix repo: https://github.com/acidanthera/nvmefix
