### ISSUE TITLE
Hi, Handoff/AirDrop question

### ISSUE THREAD

**Issue by slankka** [zearp/Nucintosh#57]
[Not working Untested](https://github.com/zearp/Nucintosh#not-workinguntested)
I saw this doc 
>
>~Handoff/AirDrop are not supported (yet) on Intel chips~ Should work now

Do you mean Handoff/AirDrop is probably working on Intel Chips (not tested yet)?

**Comment by zearp** [comment]
Some basic parts of Continuity are working like universal clipboard and Hand Off. I didn't try out everything and it's been a while so things may have improved. I compile the [Intel kexts](https://github.com/OpenIntelWireless) and test if wifi/bt works and thats about it. Not signed in to iCloud on my test machine and if something Continuity related isn't working thats out of my control.
