### ISSUE TITLE
Some driver compatibility problems of NVMeFix.kext

### ISSUE THREAD

**Issue by Martintep** [zearp/Nucintosh#58]
Thanks for your EFI.
I am a new player for the macos
I found some bugs for my nuc8i5 with HP ex900 ssd.
The NVMeFix.kext do not supported for my own ssd HP EX900.
With the NVMEix.kext I can not open my nuc8i5 to macos.
Can you remind others of compatibility issues with this driver？

**Comment by zearp** [comment]
It's not really a bug or issue with the EFI, the drive may simply not be supported (yet). It's not my driver and I can't really start curating a list of drives that work and don't work with it. Best I can do is add a note that if NVMe doesn't seem to work to disable that kext and see f that helps.

It should be fine without albeit maybe not optimally when it comes to power management and such. You'd have to check that yourself (APST/ASPM).

Once you got things installed you can make a clone to it to an (external) ssd and then boot into that using a debug ready EFI and see what it the driver detects and maybe its fixable either by you or by supplying some information to the team making the driver: https://github.com/acidanthera/nvmefix

It might be too much depending on how much into this stuff you are.
