### ISSUE TITLE
Card reader

### ISSUE THREAD

**Issue by laradvance** [zearp/Nucintosh#6]
How to enable card reader?

**Comment by zearp** [comment]
I don’t have that Dell card reader to test. It was an option for MT systems and I haven’t seen many in the wild with that reader. 

If you want to make it work you’ll have to put in some work. Like provide as many details about it as you can. How does it connect for example. I don’t have the time to look it up and then also figure out how to use it. 

Start with how it connects to the system. Also need some info from something like HWiNFO64. Like hardware id and such. Gather as much as you can. Use search engines to find if anyone else with this reader has to set it up in macOS.

I really don’t have the time to turn this issue thing in a helpdesk. I can help but need lots of info for things I don’t own. I can’t spend hours researching this as I lack the card reader itself to test anything.

**Comment by zearp** [comment]
It’s in README.md.

It only works with one release of the kext (I linked it) and it only works a bit and very slowly.

The person who made the kext is not going to support any readers he doesn’t have. This is one of them.

So you’ll have to either accept the limited usage or fix his kext to work with this card reader.
