### ISSUE TITLE
HDMI_AUDIO

### ISSUE THREAD

**Issue by sziiisz** [zearp/Nucintosh#62]
Hi, I have an NUC8i3BEH2.
Everything work fine expect the hdmi audio.
I tried to remap the connectors but without succes:/
In hackintool > peripherals > I can see just Realtek ALC235.

**Comment by zearp** [comment]
You didn't provide any of the requested information in the template nor I can reproduce this on Monterey and Big Sur. Audio over hdmi works when using usb-c and the normal hdmi connector. Maybe you have changed something else that broke it, I don't know. The connecters are mapped properly already as well. Everything works out of the box without any changes. I've just done a clean install of the latest Monterey beta the other day and everything works.

**Comment by zearp** [comment]
You didn't provide any of the requested information in the template nor can I reproduce this on Monterey and Big Sur. Audio over hdmi works when using either usb-c or the normal hdmi connector. The connecters are mapped properly already. 

Everything works out of the box without any changes other than using kexts suited for the macOS version you run. I've just done a clean install of the latest Monterey beta the other day and everything works.

**Comment by zearp** [comment]
You didn't provide any of the requested information in the template nor can I reproduce this on Monterey and Big Sur. Audio over hdmi works when using either usb-c or the normal hdmi connector. The connectors are mapped properly already, there is no need to change them.

Everything works out of the box without any changes other than using kexts suited for the macOS version you run. I've just done a clean install of the latest Monterey beta the other day and everything works as expected. Closing this.
