### ISSUE TITLE
Bluetooth failed to load after a day's sleep

### ISSUE THREAD

**Issue by ajai-akkarapaka** [zearp/Nucintosh#64]
Please provide the follow information:

- Steps to reproduce the issue -- this is crucial
- macOS version and optionally the build number - macOS 12.0.1 (21A559)
- Any changes you made to the config and/or EFI other than serials/etc - None
- Any logs related to the issue if applicable

tried all by changing kexts order and resetting nvram and loading efi from usb stick but bluetooth doesn't turn on

it was working fine after updating from Big Sur. Connections were stable until a deep sleep

**Comment by zearp** [comment]
I was able to overnight sleep test and my bluetooth mouse worked fine the next morning. It may depend on the device. I really have no clue. It is impossible for me to fix things that I can't reproduce but I will update all kexts in a few days and make a new release. Hopefully it will fix some bluetooth issues.

**Comment by ajai-akkarapaka** [comment]
Thank you for writing me back on this issue. After my last conversation, I never had an issue with regards to bluetooth since then. I had multiple times restarted, overnight deep sleep of the machine as well. So, as we had discussed, it's got to be the EFI drive corruption. Anyways will post and update if any issues arise. HAVE A GREAT DAY.

**Comment by zearp** [comment]
https://dortania.github.io/hackintosh/updates/2021/11/01/acidanthera-november.html
