### ISSUE TITLE
Possible to load, But Graphics only show Graphics 18MB.

### ISSUE THREAD

**Issue by linuxjackie** [zearp/Nucintosh#65]
Possible to load, But Graphics only show Graphics 18MB.

**Comment by linuxjackie** [comment]
Hi,
I am using NUCI5BEH,32GB Ram , Original Airport wifi,bluetooth card, Running Big Sur (upgrade from 10.15)
I am using this EFI (From internet), Which work very fine , but only the oc version not support os 12, So I found your EFI file , and tried in Big Sur and OS12, both are not load graphics kext , I didn't modify anything ,only the S/N .

[EFI.zip](https://github.com/zearp/Nucintosh/files/7445900/EFI.zip)
,
![Screenshot 2021-10-30 at 1 38 22 PM](https://user-images.githubusercontent.com/46717061/139521718-125433da-4a4f-490d-9f85-2699deece70c.png)

**Comment by zearp** [comment]
What is the full model of your NUC?

Because in the NUC8 models the graphics are supported natively. The fact you end up with this either means you changed the config or you have a different model NUC.

I can't help with this because I can't reproduce it.

**Comment by linuxjackie** [comment]
NUCI5BEH,
The EFI which I am using ,graphics are supported natively.
Thats strange......
Anyway...Thanks..

**Comment by zearp** [comment]
Thats not the full model number. It should be like NUC8i5BEK. If you have a NUC5xxxx this won't work for you. It only works for Coffee Lake NUC8 models.

**Comment by zearp** [comment]
Thats not the full model number. It should be like NUC8i5BEK. If you have a NUC5xxxx this won't work for you. It only works for Coffee Lake NUC8 models. If the current EFI would cause what you experience there would be more issues about it and I would've run into myself because I have several of these NUCs running macOS.

**Comment by linuxjackie** [comment]
It is Coffee lake,
NUC8i5BEH

**Comment by zearp** [comment]
Well then I don't know. I can't help you. But I wish you good luck.

**Comment by linuxjackie** [comment]
Hi zearp, Just a update for this , I did a Framebuffer patch by Hackintool. It fixed the problem.
Thanks for the EFI file!!!


<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>DeviceProperties</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,ig-platform-id</key>
				<data>
				BAClPg==
				</data>
				<key>AAPL,slot-name</key>
				<string>Internal@0,2,0</string>
				<key>device-id</key>
				<data>
				pT4AAA==
				</data>
				<key>device_type</key>
				<string>VGA compatible controller</string>
				<key>enable-hdmi20</key>
				<data>
				AQAAAA==
				</data>
				<key>framebuffer-fbmem</key>
				<data>
				AACQAA==
				</data>
				<key>framebuffer-patch-enable</key>
				<data>
				AQAAAA==
				</data>
				<key>framebuffer-stolenmem</key>
				<data>
				AAAwAQ==
				</data>
				<key>framebuffer-unifiedmem</key>
				<data>
				AAAAgA==
				</data>
				<key>hda-gfx</key>
				<string>onboard-1</string>
				<key>model</key>
				<string>Iris Plus Graphics 655</string>
			</dict>
		</dict>
	</dict>
</dict>
</plist>
