### ISSUE TITLE
support MacOS Monterey 12.0.1

### ISSUE THREAD

**Issue by wem2020** [zearp/Nucintosh#66]
Please provide the follow information:

- Steps to reproduce the issue -- this is crucial
- macOS version and optionally the build number
- Any changes you made to the config and/or EFI other than serials/etc
- Any logs related to the issue if applicable

- I just test lasted Stable EFI (27102021) your bootloader and make boot install MacOS Monterey 12.0.1 but can't load open core bootloader. 
- I tried with Stable EFI (07092021) boot loader is okay, but SSD nvme does not show in installation.
- My Nuc8i5be working on bigsur with your Stable EFI (07092021)

**Comment by zearp** [comment]
I can't reproduce this. And I can't help you trouble shoot why it's not working for you. On an unmodified NUC8 it works perfectly. I have tested this a few times before releasing the latest release. You can try to disable the NVMe fix up kext and see if it comes back. My test machine has an NVMe drive and it was detected there. IT could be that Monterey doesn't support your brand. Things worked in Big Sur so the would indicate to me Monterey is the issue not the EFI.
