### ISSUE TITLE
Bluetooth Does Not Work After Waking up From Sleep

### ISSUE THREAD

**Issue by metazoon** [zearp/Nucintosh#67]
- macOS 12.0.1
- I did not modify the EFI file except to add the serial number
- I followed the instructions to turn off bluetooth and wifi in the bios.
![Screen Shot 2021-10-31 at 1 39 10 AM](https://user-images.githubusercontent.com/93467632/139574804-0cd30e27-6e2b-432e-a0e8-babfaada64b5.png)
There is nothing in the Bluetooth column in normal startup
![Screen Shot 2021-10-31 at 12 21 50 AM](https://user-images.githubusercontent.com/93467632/139574659-04fa26ed-f6df-4c18-85b8-3079b5ecea9f.png)
But after waking up from sleep, the Bluetooth column has these additional things
![Screen Shot 2021-10-31 at 1 35 27 AM](https://user-images.githubusercontent.com/93467632/139574699-fad9419c-6a3a-4282-8417-b3c9ee38a0f8.png)
Apple's own Bluetooth keyboard can be connected and works, but in Bluetooth it shows that the connection is rejected. Other Bluetooth devices cannot connect.

**Comment by zearp** [comment]
Same as: https://github.com/zearp/Nucintosh/issues/64

I can't reproduce this myself but it known that Monterey has bluetooth issues with 3rd party cards.

**Comment by zearp** [comment]
I will keep an eye on fixes and updates and push them to the repo as soon as I can test they don't break anything. It will only be a matter of time before these issues are fixed by the community.

**Comment by metazoon** [comment]
I use the genuine Apple Wi-FI and Bluetooth card, BCM943602CS.

**Comment by metazoon** [comment]
> Same as: #64
> 
> I can't reproduce this myself but it known that Monterey has bluetooth issues with 3rd party cards.

I use the genuine Apple Wi-FI and Bluetooth card, BCM943602CS.

**Comment by zearp** [comment]
Then I can't help at all. I can only sort out issues wit ha stock unmodified NUC.

**Comment by zearp** [comment]
Then I can't help at all. I can only sort out issues with a stock unmodified NUC.

**Comment by metazoon** [comment]
> Then I can't help at all. I can only sort out issues with a stock unmodified NUC.

My device is a NUC 8i5beh, and what I tried to say is that I installed an Apple genuine card with an M.2 adapter.

**Comment by zearp** [comment]
I can't start helping people with their additional hardware. I don't have the time. There are better places for that. It is not related to EFI.
