### ISSUE TITLE
Not an issue :)

### ISSUE THREAD

**Issue by shrisha108** [zearp/Nucintosh#69]
Great repo, works perfectly for my wife's 8th gen i5 NUC, thank you for that. I was wondering if this can be used for 10th gen NUCs as well? Could you please point me what things have to be changed in your config in order to work for 10th gens?
Thank you very much.

**Comment by kababoom** [comment]
I have Big Sur running on a NUC10 with this EFI.

Great repo indeed.
Thank you @zearp

**Comment by gtrooper** [comment]
> I have Big Sur running on a NUC10 with this EFI.
> 
> Great repo indeed. Thank you @zearp

How sure you are that you can run this on a 10th GEN NUC ? Everyone I know insists that NUC10 is completely different

**Comment by kababoom** [comment]
To everyone you know...

![image](https://user-images.githubusercontent.com/16404944/140049288-c9b8d31e-9f09-4335-b183-b5af1df3c456.png)

**Comment by gtrooper** [comment]
Thank you very much for confirming !

**Comment by zearp** [comment]
Thanks for the kind words!

I think the main differences are the cpu generation and gpu. A new port map for usb and graphical connectors might be needed s well as changing the frame buffer settings for the gpu model. And maybe a better matching SMBIOS for the cpu, if it exists. Thunderbolt I don't know, it should work with some ACPI patches if you don't need hot plug. The other ACPI patches might need adjustment too, this can be checked easily with a DSDT dump and the Dortania guide.

**Comment by zearp** [comment]
Thanks for the kind words!

I think the main differences are the cpu generation and gpu. A new port map for usb and graphical connectors might be needed as well as changing the frame buffer settings for the gpu model. And maybe a better matching SMBIOS for the cpu, if it exists. Thunderbolt I don't know, it should work with some ACPI patches if you don't need hot plug. The other ACPI patches might need adjustment too, this can be checked easily with a DSDT dump and the Dortania guide.

**Comment by kababoom** [comment]
I've installed this one some time ago so some might be outdated but for ACPI I do use some different SSDT.

<img width="358" alt="image" src="https://user-images.githubusercontent.com/16404944/140101548-d4200e13-406f-4d2f-af19-614d50fdef75.png">

Let me know if you need more info.

**Comment by shrisha108** [comment]
Thanks so much @zearp !
@kababoom  my NUC 10th coming on a next Monday. WIll probably ask you for yours aml files :)

**Comment by kababoom** [comment]
@shrisha108 this one is working fine....
https://github.com/hackintosh-efi/intel-nuc10
