### ISSUE TITLE
Not an issue, just a stupid newbie question

### ISSUE THREAD

**Issue by Badsheep** [zearp/Nucintosh#71]
Hello,

I have a NUC8i3BEH2 and I’m about to try to use your work, so thanks in advance.

I just have a stupid newbie question… I’m sorry that’s my first hackintosh.

when you talk about the Mac adress, I dont understand : am I suppose to use a fake one, like described in the link you give ? (https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#fixing-en0)

I choose the begining in the list and make up the 6 other digits ?

or do I have to use my real mac adress ? And in this case is it the Mac adress of the Mac (or pc) on which on will run GenSMbios ?

If anybody could  explain this part to me it would be really nice !

thanks !

**Comment by zearp** [comment]
You can either use the real one (it's on the box of the NUC too) or you make one up. It's up to you.

**Comment by Badsheep** [comment]
Thank you very much for your help and your work !
