### ISSUE TITLE
HDR option missing

### ISSUE THREAD

**Issue by SeaDaddytheRed** [zearp/Nucintosh#74]
Hello, I have a LG 27GL850 monitor hooked up to the NUC by HDMI.  In Windows and Big Sur HDR worked no problem but since upgrading to Monterey the HDR option has disappeared in the Display settings.

Looking around the net this might be a Monterey issue but I just wanted to check here if anyone else is having HDR problems.

**Comment by zearp** [comment]
I have no screens with HDR to test this with. I'm unsure if this is caused or fixable by changes in the EFI. You may have to setup a custom profile for the monitor. If it works with the EFI in Big Sur but not in Monterey I'm inclined to blame Monterey.

**Comment by SeaDaddytheRed** [comment]
Thanks for the reply.  I actually found [this](https://github.com/alexjohnj/LG27GL83A-edid-patches/issues) for my specific monitor.  I am asking if he can help me.
