### ISSUE TITLE
Fans running on high speed always

### ISSUE THREAD

**Issue by ajai-akkarapaka** [zearp/Nucintosh#75]
Hi Zearp.

Post new stable EFI and update to 12.1 the fans are always running high above 4000 rpm. Is it common? Since this was not there before ever.

I have changed the fan setting in BIOS to quiet but still the fans are running high for very normal operations such as web browsing and small office works

Please provide the follow information:

- Steps to reproduce the issue -- this is crucial
- macOS version and optionally the build number  12.1
- Any changes you made to the config and/or EFI other than serials/etc - None
- Any logs related to the issue if applicable
![Screen Shot 2021-12-26 at 12 20 18 PM](https://user-images.githubusercontent.com/85277762/149380485-e866709d-2d5a-4bfb-9112-55e0f15fdac3.png)

**Comment by zearp** [comment]
I can't reproduce this. I'm running several NUCs all running Monterey and have not run into any fan issues whatsoever. The fan speeds are not controlled by the EFI, if anything the EFI reduces the temperatures by lowering the idle CPU clock speeds and such using the CPUFriend kexts.

**Comment by ajai-akkarapaka** [comment]
Thank for the reply..
I guessed the same as you said but still wanted to ask you before I re-install the OS.
Anyways, will try finding the cause and update you if I find any

**Comment by zearp** [comment]
I did notice on some NUCs the thermal paste is not ideal which results in higher temps and it's quite a hassle to re-apply it. I would check temps and fan behaviour in macOS and Windows if I were you. Let me know if there's any big differences. My NUCs idle around 35-40c depending on ambient temps and fan curve in the BIOS. I do set my fan curve like Apple does, no fan until it's really needed at around 70-80c.

On some of my NUCs the fans come on too quickly for my liking, a short burst of something intensive and they ramp up whilst its not really needed. Luckily we can tweak the fan curves quite well in the BIOS. If you're comfortable at running at higher temps these tiny machines can be near silent unless you push them for a prolonged time.

I don't mind them running a bit hot when I'm compiling something or unpacking a large archive. These Intel CPUs can run near 100c without triggering thermal throttling. My 2018 MacBook Pro (same i5 CPU) goes to 90c before the fans ramp up.

**Comment by zearp** [comment]
For monitoring temps I would suggest Intels own tool. It's likely the most accurate. 

https://www.intel.com/content/dam/develop/external/us/en/documents/downloads/intel-power-gadget.dmg

**Comment by ajai-akkarapaka** [comment]
I will check and update you soon.. I did notice that the temperature range is somewhere between 60 to 70c on most times when the fans kick in. Therefore, I will try dismantling the NUC and re-apply new thermal paste to see if there is any changes in the machine.
.

**Comment by zearp** [comment]
Idle temps between 60-70 re too high. Check the CPU usage using activity monitor for anything using a lot of it.

**Comment by zearp** [comment]
Idle temps between 60-70 are too high. Check the CPU usage using activity monitor for anything using a lot of it.

**Comment by ajai-akkarapaka** [comment]
have been checking and diagnosing these for the past 20 days.. there is no activities that have been using as you see from the screen shot, my data for the last month shows everythin
![Screen Shot 2022-01-16 at 10 04 38 AM](https://user-images.githubusercontent.com/85277762/149647426-555d11ef-2139-4ddb-9785-e40703f16b27.png)
![Screen Shot 2022-01-16 at 10 03 43 AM](https://user-images.githubusercontent.com/85277762/149647429-87bba5ad-26a1-4646-b3f2-b512c9e45619.png)
g

**Comment by zearp** [comment]
Does the same happen in Windows or Linux?

**Comment by ajai-akkarapaka** [comment]
I have only macOS installed.

**Comment by zearp** [comment]
Ok, well I don't think its related to the EFI and since you're unable to compare there's not much else I can do other than make the suggestion I made earlier. If I were you I'd make a custom fan profile and also stress test the machine to see if the highest fan speeds actually cool it down. IT could be as simple as thermal paste not being applied properly or too little or too much. Either way I don't think this is related or caused by the EFI.

**Comment by zearp** [comment]
Ok, well I don't think its related to the EFI and since you're unable to compare there's not much else I can do other than make the suggestions I made earlier. If I were you I'd make a custom fan profile and also stress test the machine to see if the highest fan speeds actually cool it down. It could be as simple as thermal paste not being applied properly or too little or too much. Either way I don't think this is related or caused by the EFI.
