### ISSUE TITLE
[NUC8i5BEH] - upgrade to macOS 12.3 RC, boot failed

### ISSUE THREAD

**Issue by Quanuanc** [zearp/Nucintosh#78]
Please provide the follow information:

- Steps to reproduce the issue -- this is crucial
    upgrade from 12.2.1 to 12.3 RC, while install success, nuc will reboot, then will stuck in the boot proccess.

- Any changes you made to the config and/or EFI other than serials/etc
   1. add AirportBrcmFixup.kext for bcm943602cs card
   2. delete some kexts: AirportItlwm.kext, BlueToolFixup.kext, IntelBluetoothFirmware.kext 
   3. use [ProperTree](https://github.com/corpnewt/ProperTree)'s OC Clean Snapshot (Cmd+Shift+R) to walk the contents of Kexts for OpenCore config.plist files

- Any logs related to the issue if applicable
![IMG_0502](https://user-images.githubusercontent.com/37785611/158044567-0ac2c55d-2380-417d-b436-e356a0eb1cb2.jpg)

**Comment by zearp** [comment]
No such issue on my test machine running macOS 12.3 (21E230). It was upgraded using Software Update.

Disable any additional kexts to rule out any of those cause your boot failure.

If that doesn't work. Try a usb install on top of what you have now using an unmodified version of the EFI. You can disable kexts you don't need but don't add anything until install is complete. Boot with a 12.3 installer and install it on top of your existing one. No data or settings will be lost.

Unfortunately the log isn't helping, there's no crash showing or anything jumping out that gives the reason why it's stalling. It is stalling there right? Or do you get a boot-loop?

**Comment by zearp** [comment]
The last messages in your log relate to AirportBrcmFixup.kext -- if it's the cause then it may not be ready for 12.3 yet.

**Comment by Quanuanc** [comment]
I found a way to pass it, but it's strange. 
When my nuc starts up, if 4K resolution screen is connected at this time, it will get stuck. But when i  use a  2K resolution  screen at startup, it can start up normally. Both of them are connected by thunderbolt interface.

**Comment by zearp** [comment]
I'm happy you fixed it. It is very weird indeed. I can't test it because I don't have any Thunderbolt screens.

**Comment by Quanuanc** [comment]
Just update some information.

If someone has a problem like me (unable to boot successfully in a 4K screen, but can boot successfully in a lower resolution screen), you can add `igfxagdc=0` boot argument to `boot-args` in opencore's config.plist.

I don't know what it does, but it does work for me.

**Comment by zearp** [comment]
It toggles AGDC, it is enabled by default. Very interesting find. Seems to be causing issues with certain 4k screens for a while now. I'm not sure if we need AGDC enabled, will do some tests when I have more time for it and turn it off by default if its not needed. Thanks!

**Comment by vardumper** [comment]
I agree with @Quanuanc. Your work is appreciated Mr. zearp!
