### ISSUE TITLE
bluetooth of BCM943224PCIEBT2

### ISSUE THREAD

**Issue by hdchieh** [zearp/Nucintosh#79]
- macOS version: Monterey 12.3

When I was using Big Sur with AirportBrcmFixup.kext, everything is ok.
Now I update the system to Monterey; the wifi is working but bt not.

I added
-`                <dict>
                    <key>Arch</key>
                    <string>Any</string>
                    <key>Base</key>
                    <string></string>
                    <key>Comment</key>
                    <string>Whitelist BCM943224PCIEBT2</string>
                    <key>Count</key>
                    <integer>0</integer>
                    <key>Enabled</key>
                    <false/>
                    <key>Find</key>
                    <data>TWFjLTJFNkZBQjk2NTY2RkU1OEM=</data>
                    <key>Identifier</key>
                    <string>com.apple.driver.AirPort.Brcm4360</string>
                    <key>Limit</key>
                    <integer>0</integer>
                    <key>Mask</key>
                    <data></data>
                    <key>MaxKernel</key>
                    <string></string>
                    <key>MinKernel</key>
                    <string></string>
                    <key>Replace</key>
                    <data>TWFjLTdCQTVCMkRGRTIyREREOEM=</data>
                    <key>ReplaceMask</key>
                    <data></data>
                    <key>Skip</key>
                    <integer>0</integer>
                </dict>`

-`                <key>PciRoot(0x0)/Pci(0x1C,0x0)/Pci(0x0,0x0)</key>
                <dict>
                    <key>AAPL,slot-name</key>
                    <string>Internal@0,28,0/0,0</string>
                    <key>device_type</key>
                    <string>Network controller</string>
                    <key>model</key>
                    <string>BCM43224 802.11a/b/g/n</string>
                    <key>brcmfx-country</key>
                    <string>#a</string>
                    <key>brcmfx-driver</key>
                    <string>2</string>
                </dict>`

-[AirportBrcmFixup.kext]

I have checked PciRoot/slot-name paths and deleted AirPortBrcm4360_Injector.kext plug-in. 
still the wifi is working and bt not.
I wonder if I miss something. Thanks.

**Comment by hdchieh** [comment]
I add BlueToolFixup.kext, and it's working. 😭  so, is there four prerequisites for the bt to work?
BlueToolFixup.kext, AirportBrcmFixup.kext, and the two snippets above?

**Comment by zearp** [comment]
Monterey requires the use of the BlueToolFixup kext for certain cards, this kext has been included for a while now.

The BCM943224PCIEBT2 will not work properly in Monterey anymore. You will need to use the OpenCore Legacy Patcher or something similar that restores older macOS networking kexts to get it working. This wil also include disabling SIP. I don't recommend disabling security features.

Upgrading to a slightly newer card (BCM94360CS2) is the easiest way to solve this issue if you require Monterey.
