### ISSUE TITLE
Rebooting Randomly

### ISSUE THREAD

**Issue by TwEnTy90** [zearp/Nucintosh#80]
Hi, i have a problem with lastest two Efi. When the NUC is sleep or downloading torrent, Intel NUC is rebooting. How i resolve this problem? My Russian Friend Anthony help me to install Hackintosh but we do not understand Why hack rebooting automatic. Please Zearp help me.

**Comment by zearp** [comment]
It is difficult to solve random reboots. For me to help I must be able to reproduce the issue. If you have steps I can follow so it always happens then I can help out. I haven't run into any of the issues myself. I have a few NUCs running the latest EFI.

Can you tell me in what version it never happens and when it started to happen? The changes between those versions might give some clues to whats going on. 

Also check your logs for anything around the time the reboot happened and check for panic logs. Please also enable verbose booting and make sure the boot arguments include ```debug=0x100 keepsyms=1```.

Make sure ```AppleDebug``` and ```ApplePanic``` are enabled too in the config. With these settings it might generate a crash/panic log or show something on screen when it crashes. We need as much information as possible.

Did you make any changes to the config?

**Comment by TwEnTy90** [comment]
Hi, to day i Will erase macOS and i Will a clean install with lastest efi. I hope to resolve the problem. Can i change only the smsbios, because when i modify the smbios it change to i7.

**Comment by TwEnTy90** [comment]
@zearp Hi Zearp, I can confirm that once I reinstalled Monterey with the latest EFI the problems related to random reboots are resolved. thank you so much for your support.
