### ISSUE TITLE
Apple Music and Amazon Prime videos DRM issues

### ISSUE THREAD

**Issue by Badsheep** [zearp/Nucintosh#81]
Hello,

is there a possible workaround to have the Apple Lossless Music working ? And / or Amazon Prime.

I have Netflix working, but the two stuffs above are not working.

my EFI and kext are not up-to-date, would an upgrade change anything ?
I installed my NUC few months ago.

thanks for tour great work zearp !

**Comment by zearp** [comment]
It is not possible. Some video related DRM can be used if your use a macOS supported eGPU in a Thunderbolt enclosure. Some streaming DRM will work at lower resolution in 3rd party browsers. But as a general rule if you need DRM stuff on mackintosh you're in for a rough ride.

You're welcome! You don't need to update unless a macOS update breaks something. When it works, it works. It's very rare macOS updates break something that causes macOS to stop booting. I would suggest to update before upgrading to a new macOS version. It can't hurt and sometimes there are some improvements relating to speed or stability.

**Comment by Badsheep** [comment]
Ok thanks for your explanations !

**Comment by Tobix99** [comment]
Hey, short question: Does your Apple Music "Streaming" work? I can only listen to Apple Music songs when they are downloaded, otherwise when "just" listening (streaming) them, they will skip. I think this is the described DRM Problem, but I thought, that this is only with Lossless Streaming?

**Comment by Badsheep** [comment]
Yes it works in AAC 256 kbit.
Only Lossless doesn't work.

**Comment by Tobix99** [comment]
Ahh so I've found the "problem". Streaming works when you output to any device other than AirPods Pro or AirPods Max. When selecting those only downloaded, 256kbits AAC Songs work. Otherwise it'll skip like crazy.

And Download in Lossless also doesn't work.

**Comment by zearp** [comment]
For Bluetooth audio streaming it can sometimes help to force either aptX or AAC codecs. This can be done with the Bluetooth explorer tool. You can also tweak bit rates and some other things they can improve quality and latency. The tool should be in the Xcode additional tools package. It wasn’t in the latest Xcode beta but should be in an older stable release. Too bad macOS doesn’t support more modern Bluetooth codecs. The new aptX ones and LDAC would be great but Apple loves AAC 😅

**Comment by Badsheep** [comment]
To listen Lossless music on my Nucintosh here is my setup : 

- I stream Apple Lossless Music on a iOS device (an iPhone)
- I send it (in lossless too, in Wifi) on [Airfoil Satellite](https://rogueamoeba.com/airfoil/satellite/) 
- Then I have a good sound card and good speakers connected to my Nucintosh.

**Comment by Tobix99** [comment]
@zearp thanks for the Advice, I "fixed" the issue...I can now Stream Apple Music via Bluetooth to my AirPods Pro (using a BCM94360CS2-Card).

1. Download "Additional_Tools_for_Xcode_11.4.dmg" from Apple (newest Version, where the "Bluetooth Explorer" is included).
2. Add "Hardware->Bluetooth Explorer" to local Application Folder
3. Start "Bluetooth Explorer"
4. Go to the "Top"-Application-Bar, then Tools->Audio Options...
5. There select "Force use of aptX" and "Disable AAC" (I'm not sure, if both are needed, have to do some "research")
6. Click "Close"
7. Restart the Mac

With this Method it works™, but I don't know yet, if these options have any negative consequences.

![image](https://user-images.githubusercontent.com/22603015/193103121-14c946d0-bd3c-4dc3-8e2f-1446cf16514e.png)

**Comment by zearp** [comment]
I'm happy it helped!

In my experience some headphones perform a lot better with the settings tweaked. There's no downside unless you have another bluetooth headphone which works better with different settings.

As it seems Big Sur and newer do not properly support the tool anymore and Apple has not included it in Xcode 12/13. I wonder why and if anything will be released that replaces it. I'm not holding my breath but who knows!

There are terminal commands that can enable AptX and disable AAC in Big Sur and newer but this tool is really nice not only for bluetooth audio issues.

**Comment by zearp** [comment]
These are defaults on my Ventura install. I've not tested if it actually works in Ventura. Some people say it doesn't work, some say it does. I do wonder why Apple has removed the bluetooth explorer tool.

![Screenshot 2022-10-01 at 12 38 15](https://user-images.githubusercontent.com/63272687/193405570-644f42f9-0b7f-4287-a517-72cf5e00e82b.png)
