### ISSUE TITLE
Wanted to share something.

### ISSUE THREAD

**Issue by naryfa** [zearp/Nucintosh#83]
Please forgive me for creating this issue on GitHub, I have no other way of contacting you. I guess you can just close it after reading.

I still have my trusty Mojave install from your repo. So I wanted to show my gratitude by sharing this:

I recently bought NUC7/NUC8 **Cirrus7** case because I didn't like the Akasa one. This one has nice, rounded finish in silver. It was well worth the money. Now my Nucintosh idles at 28℃ with i7-8559u. It's unbelievable. The original NUC housing with the fan put it at 36℃ when the room was cold. 

I'm really thankful for all your hard work. I can't even express it well enough. You made my little computer work for years now. The only other machine I've got is 2010 MacBook Air. On a different note, it's saddening how Apple is directing their hardware design into planned obsolescence. Perhaps you'll find it worthwhile to check out this video by Hugh Jeffreys:

https://www.youtube.com/watch?v=oYhRPiVPA3c

**Comment by zearp** [comment]
Thank you for the kind words!

I have several of these little NUCs purring away for years now. They are very reliable specially without any moving parts. I will check out the case you got! Sounds good and I have some that are still in their small noisy cases.

I've watched his Apple videos and those by Louis Rossmann too. The latter has some great rants showing all the hardware design fils over the years. Always showing Apple's famous "a small percentage" statements lol.

I'm expecting Ventura to run just fine but I don't know what comes after. Apple will have less and less reason to optimise things for Intel. Monterey runs snappy enough but when I did some testing in Catalan the other day I was amazed how much more responsive it feels. It might not be faster just less fades and fancy stuff. Catalina gets to the point.

Just finished updating to OpenCore 0.8.2 here and it seems to works good on Monterey. Other than Intel's bluetooth which for some reason stopped working on my test machine. Intel wireless is fine. I. don't use either of them in my own normal NUCs, they're all upgraded with Apple Airport cards. I don't really need the NVMe speed. I rather have all the Hand Off and Continuity working properly. Universal Control worked out of the box for me too.

The last Mac I bought is a bit newer than you but I stopped buying their computers and laptops years ago. A well configure OpenCore gives me the same experience as my real Macbook. Including the same macOS bugs haha. Specially bluetooth!

I'll open an issue for the brave souls that want to try Ventura or try 0.8.2. I wouldn't recommend updating the EFI unless you need to. If it works it works. I have some NUCs still on OpenCore 0.7.x and they are doing just fine.

Good luck and have fun!

**Comment by naryfa** [comment]
PS. Did the same thing, used OEM Apple WiFi/BT in the NVMe slot and stuck in a SATA drive. 👍

Again, thank you so much for your efforts on this.
