### ISSUE TITLE
Compatibility of this EFI for "New Model" Intel NUC 8 Pro Kit NUC8i3PNH  ?

### ISSUE THREAD

**Issue by gtrooper** [zearp/Nucintosh#85]
Hi @zearp ! I wanted to say a huge thanks for the amazing work you do all these months ! Just a quick question if you can help. 3 years ago I bought the NUC8i7BEH which is what I currently use with your EFI and it works amazingly well ! I do not want to buy the 10th Gen NUC because it has a worse iGPU and while initially I wanted to buy the 11th Gen NUC, sadly the iGPU was never supported on this model. So.. I need 3 more NUC8 Nucs and I cant find them new anywhere... Recently I discovered that Intel Released a "New" NUC8 with name Intel NUC 8 Pro Kit  *NUC8i3PNH* ! Do you know if this NUC with 2 HDMI's on the back (See Attached Image) is compatible with your EFI ? Thank you so much for everything you do 
!
[Intel NUC8 Pro NUC8i3PNH ](https://user-images.githubusercontent.com/43722469/178265625-0710ba06-c3ce-4b1b-8b1e-1c22f65607d0.jpeg)
!

**Comment by zearp** [comment]
I don't have that model so I can't really test If it uses the same chipset and other parts as the earlier NUC8's it should work but you may need to make a new connectors map for the dual HDMI ports to work properly. Things will probably work without making such map but it's recommended to make one just so macOS knows exactly what each connector is. This is important in multi display setups.

I've seen Amazon sells the early NUC8 models for quite cheap a while ago. Maybe they were selling off the remaining stock. I'm seeing another new NUC8 model available for pre-ordering that has dual HDMI and an AMD Radeon card: NUC8I3CYSN2. It's kind of funny Intel is still releasing new 8th gen NUCs. I don't think mobile AMD chipsets are supported in macOS but if this one is then DRM might work. Would be a good option for HTPC ifDRM can be made to work on the AMD model.

Detailed specs for the model you mentioned can be found here: https://www.intel.com/content/dam/support/us/en/documents/intel-nuc/NUC8v5PN-NUC8v7PN-TechProdSpec.pdf

It comes with a different graphics chip compared to the older models. This one is weaker, UHD 620 vs, Iris Pro 655 in the older models. Both should work ok with macOS but you'll have to make a new framebuffer config. It will also most likely need a new usb map. As for ACPI patched, you'll have to boot one up with sysReport enabled in the OpenCore config to make new ACPI dumps and then check if the CPI patches are still ok for or need to be adjusted. DVMT and CFG Lock stuff might also be an issue, or not. There are some variables that are difficult to predict without owning the hardware.

All in all macOS can probably made to work on them usb a stables on the older models but it may take more work that excepted. There's usually some unforeseen things that cost more time to sort out.

I'll keep an eye on the prices for the new 8th gen NUC models and pick one up if they drop enough.
