### ISSUE TITLE
Ventura Cpu Name

### ISSUE THREAD

**Issue by TwEnTy90** [zearp/Nucintosh#87]
[EFI.zip](https://github.com/zearp/Nucintosh/files/9127389/EFI.zip)

Hi Zearp!,

I have installed Ventura succeffuly with your EFI. But I Have a question, I have modify the SMBIOS for iMessage and FaceTime, now they work. But the machine reconize that I have a i7. I have an i3, can I change this? Can you modify my efi? 

Thank's for your work

**Comment by zearp** [comment]
What did you change the SMBISO to? The EFI you posted has the default SMBIOS (Mac mini 8,1). It should not be needed to change the SMBIOS from the default for iServices to work.

**Comment by TwEnTy90** [comment]
[Screenshot 2022-07-17 alle 13.50.17.zip](https://github.com/zearp/Nucintosh/files/9127536/Screenshot.2022-07-17.alle.13.50.17.zip)

How to see in the screenshot, I would to change i7 to i3. Could it affect performance since on the information on this mac I see i7 instead of i3?

**Comment by zearp** [comment]
You did not answer my question. Also this is a cosmetic issue likely not caused by the EFI but by you changing the SMBIOS for some reason.

**Comment by TwEnTy90** [comment]
I had to change the SMBIOS because the one you set by default did not connect to Imessage and Facetime. When I changed the SMBIOS, it changed the CPU model accordingly. And I was wondering, could this change the CPu's performance? Because it actually warms up.

**Comment by TwEnTy90** [comment]
Another thing I noticed is that when you change the resolution (I have a 4k monitor) the system gets all laggy. When I set the resolution in 4k the animations are perfect. He also had this problem with Monterey.

**Comment by zearp** [comment]
Nobody else has reported any off these issues nor have I run into any of them myself. You're the first person who "needs" to change SMBIOS for iservices to work.

I can't and won't help with a non-standard install.

It is also difficult to help when you don't even answer my basic questions like to what SMBIOS you had changed it. Good luck!

**Comment by zearp** [comment]
Nobody else has reported any off these issues nor have I run into any of them myself. You're the first person who "needs" to change SMBIOS for iServices to work.

I can't and won't help with a non-standard install.

SMBIOS controls al lot including voltages and frequencies. You should use the default SMBIOS and try to fix your iService issues the normal way: https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html

It is also difficult to help when you don't answer my questions like to what SMBIOS you had changed it to.

Good luck!

**Comment by zearp** [comment]
Nobody else has reported any off these issues nor have I run into any of them myself. You're the first person who "needs" to change SMBIOS for iServices to work.

I can't and won't help with a modified EFI/non-standard install.

SMBIOS controls a lot including voltages and frequencies, using the wrong one can lead to many issues. You should use the default SMBIOS of the Mac mini 8,1 and try to fix your iService issues the normal way: https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html

Good luck!

**Comment by zearp** [comment]
Nobody else has reported any off these issues nor have I run into any of them myself. You're the first person who "needs" to change SMBIOS for iServices to work.

I can't and won't help with a modified EFI/non-standard install.

SMBIOS controls a lot including voltages and frequencies, using the wrong one can lead to many issues. You should use the default SMBIOS of the Mac mini 8,1 and try to fix your iService issues the normal way: https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html -- make sure you log out before changing the SMBIOS back to the default and also clean NVRAM and wipe previous attempts as the bottom of the page explains [here](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#clean-out-old-attempts).

Good luck!

**Comment by zearp** [comment]
Nobody else has reported any off these issues nor have I run into any of them myself. You're the first person who "needs" to change SMBIOS for iServices to work.

I can't and won't help with a modified EFI/non-standard install.

SMBIOS controls a lot including voltages and frequencies, using the wrong one can lead to many issues. You should use the default SMBIOS of the Mac mini 8,1 and try to fix your iService issues the normal way: https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html

Read it all carefully before doing anything and make sure you follow the steps in the ```Cleaning up your AppleID``` and ```Clean out old attempts``` sections.

Good luck!
