### ISSUE TITLE
failed after installation first reboot

### ISSUE THREAD

**Issue by yumoqing** [zearp/Nucintosh#88]
Hi, I has a NUC8i5BEH, and original NVMe hd runs a windows 11,  I follow the steps there, and the installation start very well, and restart, after the boot into OC options, I choose the "install Monterey", and after this point, it will restart again and again

if I switch boot from the inter-disk, it begin to repairs the windows

at the first boot from usb, I had select the "reset NVRAM".

What is wrong with me?

the follows is detail steps I did

1. download Monterey from apple. and create the usb install disk
2. mount the EFI partition of USB
3. delete EFI folder from EFI partition on USB
4. copy this repo's EFI folder to EFI partition on USB
5. use GenSMBIOS gen the systeminfo and update the config.plist file in EFI/OC folder on EFI partition(just four fields)
6. umount the all partitions on USB
7. update NUC's bios to 0089 and change the options list in readme.md
8. set boot from ups first
9. reboot nuc
10. select reset NVRUM from oc menu
11. reboot
12. select "Monteray installer ...?"
13. disk partition 
14. installation
15. reboot automatically
16. select "install Monterey" from oc menu
17. restart loop forever, no oc menu display

**Comment by zearp** [comment]
What we dactyl is it doing when it’s looping? You say it doesn’t even show the OpenCorr menu. It is a confusing issue to understand for me. I do clean installs often and never run into boot loops. I can’t reproduce this and I can’t help without logs and informstion such as the config you used. It is impossible you have a silent boot loop with nothing showing on the screen. If the OpenCore menu it not even shown then something is very wrong with your computer. Good luck!
