### ISSUE TITLE
CAFONE!!!!

### ISSUE THREAD

**Issue by TwEnTy90** [zearp/Nucintosh#89]
Thanks for closing the thread I created. I only asked you if you could help me to best configure the SMBIOS because it displays me as a processor an i7 instead of i3. After I explicitly told you that WITH YOUR SMBIOS, it did not let me log in with messaging services, you replied that I DO NOT REPLY YOUR QUESTION.

I'll get help elsewhere, thanks for your not helping.

**Comment by zearp** [comment]
Thanks for being so entitled.

**Comment by zearp** [comment]
Did you even bother to read what I explained to you [here](https://github.com/zearp/Nucintosh/issues/87#issuecomment-1186683370)? As long as you don't use the default SMBIOS I'm not gonna help you. Also you don't have the right to my support or time. I do this for fun and people like you who act entitled take away the fun. Be happy people like me put in time and effort to share their work on Github for everybody to use and learn from and build up on.
