### ISSUE TITLE
Boot loop Monterey

### ISSUE THREAD

**Issue by nsc80** [zearp/Nucintosh#93]
Hello. First of all great work!
I have an issue. With Catalina all goes smoothly. 
I made a boot drive with your EFI and Monterey installer.
I can install, but after I get stuck in a boot loop. Any thoughts?
Thanks

**Comment by zearp** [comment]
I would a lot more details, details on hardware, any changes form stock, software versions used, steps on how to reproduce it etc. I did a few clean installs of Monterey and Ventura recently without any issues ons my stock test NUC.

**Comment by zearp** [comment]
I need more details, details on hardware, any changes form stock, software versions used, steps on how to reproduce it etc. I did a few clean installs of Monterey and Ventura recently without any issues on my stock test NUC using the release EFI.

Make sure you use the correct version of the wifi kext. If you boot with mismatching kexts a boot loop might be the result. If you want to multi boot you have to add min/max versions and add all versions of the wifi kext you need or use the itlwm kext and Heliport to connect to a wifi.

https://github.com/OpenIntelWireless/HeliPort

**Comment by zearp** [comment]
I need more details, details on hardware, any changes from stock, software versions used, steps on how to reproduce it etc. I did a few clean installs of Monterey and Ventura recently without any issues on my stock test NUC using the release EFI.

Make sure you use the correct version of the AirportItlwm kext. If you boot with mismatching kexts a boot loop might be the result. If you want to multi boot macOS versions you have to rename the wifi kexts and add min/max versions to them in the config so the right one loads with a matching macOS or use the itlwm kext and Heliport to connect to a wireless network.

https://github.com/OpenIntelWireless/HeliPort
