### ISSUE TITLE
Feature Request: add a fancy Theme

### ISSUE THREAD

**Issue by vardumper** [zearp/Nucintosh#94]
I use this EFI for my other NUC10: https://github.com/hackintosh-efi/intel-nuc10
And I like the boot optics better. If this ain't much of a hassle, could you add the same theme to Nucintosh? Cheers.

**Comment by zearp** [comment]
Thanks for your suggestion! It is very easy to add this yourself and not really in the scope of my idea of what a base EFI should belike. I want to provide an EFI that can be used as stable base, small and lean. It is not by accident verbose booting is enabled and no theme was included. Adding a theme is something to do post install. I personally prefer disabling verbose boot and the OpenCore picker all together once the system works as it should. Booting will be slightly faster and if you need the picker menu you hold down alt while booting like on a Mac. I might add a little how to to the post instal section explaining how to add a theme but I won't include it by default if only to keep the size of the EFI and releases small.
