### ISSUE TITLE
Reboot loop after install

### ISSUE THREAD

**Issue by naryfa** [zearp/Nucintosh#95]
Hey,

While trying a fresh Monterey install on a new SATA SSD I get the reboot loop. 

I have replaced the Airportltlwm.kext with the one from Stuff designated for Monterey. I have even removed it from EFI altogether. But nothing helps.

I guess I should also remove the records from the config.plist?

It's weird that the installer starts, but once installed the drive won't boot. Even though it's the same EFI (newest updated). It just loops.

https://user-images.githubusercontent.com/38587586/188502557-929cffa5-120b-41f0-a22d-fe46934ff9f0.MOV

**Comment by naryfa** [comment]
I re-did the OC snapshot after removing the kexts, and also used APFS this time and it worked. Not sure whether due to redoing the snapshot, or APFS, or both. Anyhow, it has installed.

Thank you.

**Comment by zearp** [comment]
What version of Monterey did you use to install? I can try to reproduce it but I need to know the version used to create the installer.

**Comment by naryfa** [comment]
The latest download from Apple.

**Comment by zearp** [comment]
I did a clean install with 12.5.1 a few days ago and I couldn't reproduce this issue. I can only fix things can reproduce on my stock NUC.

**Comment by zearp** [comment]
I did a clean install with 12.5.1 a few days ago and I couldn't reproduce this issue. I can only fix things I can reproduce on my stock NUC. I even ask in the template to provide steps to reproduce.
