### ISSUE TITLE
DRM content with iGPU

### ISSUE THREAD

**Issue by naryfa** [zearp/Nucintosh#98]
Hey Zearp,

So I was reading this article and got curious. What SMBIOS are you using on your NUCs? I've got MacMini8,1 and according to this Dortania article, it won't work with Apple TV or Apple Music Lossless. 

Would do you think?

I post the link to the article:

https://dortania.github.io/OpenCore-Post-Install/universal/drm.html#testing-hardware-acceleration-and-decoding

**Comment by zearp** [comment]
What’s your question or issue?

**Comment by zearp** [comment]
DRM only works with dGPU and only with older macOS version. Please refer to this chart. If you want to play all DRM content on your NUC you will need a Thunderbolt eGPU case and a macOS compatible dGPU. But even you will need to run older macOS to play most DRM content.

https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md

**Comment by zearp** [comment]
DRM only works with dGPU and only with older macOS versions. Please refer to this chart. If you want to play all DRM content on your NUC you will need to run Catalina or earlier, have a Thunderbolt eGPU case and a macOS compatible dGPU.

https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md
